# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2024-10-18T00:13:39+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


class PageInfo(BaseModel):
    level: Optional[str] = None
    pageUrn: Optional[str] = None
    statusCode: Optional[int] = None


class Data(BaseModel):
    artwork_url: Optional[str] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: Optional[str] = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    managed_by_feeds: Optional[bool] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    public: Optional[bool] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    user_id: Optional[int] = None
    set_type: Optional[str] = None
    is_album: Optional[bool] = None
    published_at: Optional[str] = None
    display_date: Optional[str] = None
    user: Optional[str] = None
    tracks: Optional[List[str]] = None
    track_count: Optional[int] = None
    urn: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    collection: Optional[List[str]] = None
    next_urns: Optional[List] = None
    offset: Optional[int] = None
    limit: Optional[int] = None
    fetchingMore: Optional[bool] = None


class SoundcloudPlaylists1809366229(BaseModel):
    status: Optional[str] = None
    data: Optional[Data] = None


class Data1(BaseModel):
    artwork_url: None = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: Optional[str] = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    managed_by_feeds: Optional[bool] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    public: Optional[bool] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    user_id: Optional[int] = None
    set_type: Optional[str] = None
    is_album: Optional[bool] = None
    published_at: Optional[str] = None
    display_date: Optional[str] = None
    user: Optional[str] = None
    tracks: Optional[List[str]] = None
    track_count: Optional[int] = None
    urn: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    collection: Optional[List[str]] = None
    next_urns: Optional[List] = None
    offset: Optional[int] = None
    limit: Optional[int] = None
    fetchingMore: Optional[bool] = None


class SoundcloudPlaylists1794053211(BaseModel):
    status: Optional[str] = None
    data: Optional[Data1] = None


class Playlists(BaseModel):
    soundcloud_playlists_1809366229: Optional[SoundcloudPlaylists1809366229] = Field(
        None, alias="soundcloud:playlists:1809366229"
    )
    soundcloud_playlists_1794053211: Optional[SoundcloudPlaylists1794053211] = Field(
        None, alias="soundcloud:playlists:1794053211"
    )


class PublisherMetadata(BaseModel):
    id: Optional[int] = None
    urn: Optional[str] = None
    contains_music: Optional[bool] = None


class Format(BaseModel):
    protocol: Optional[str] = None
    mime_type: Optional[str] = None


class Transcoding(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media(BaseModel):
    transcodings: Optional[List[Transcoding]] = None


class Data2(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1932437078(BaseModel):
    status: Optional[str] = None
    data: Optional[Data2] = None


class Transcoding1(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media1(BaseModel):
    transcodings: Optional[List[Transcoding1]] = None


class Data3(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media1] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1928806370(BaseModel):
    status: Optional[str] = None
    data: Optional[Data3] = None


class Transcoding2(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media2(BaseModel):
    transcodings: Optional[List[Transcoding2]] = None


class Data4(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media2] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1924690475(BaseModel):
    status: Optional[str] = None
    data: Optional[Data4] = None


class Transcoding3(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media3(BaseModel):
    transcodings: Optional[List[Transcoding3]] = None


class Data5(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media3] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1919519162(BaseModel):
    status: Optional[str] = None
    data: Optional[Data5] = None


class Transcoding4(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media4(BaseModel):
    transcodings: Optional[List[Transcoding4]] = None


class Data6(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media4] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1915339064(BaseModel):
    status: Optional[str] = None
    data: Optional[Data6] = None


class Transcoding5(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media5(BaseModel):
    transcodings: Optional[List[Transcoding5]] = None


class Data7(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media5] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1911442859(BaseModel):
    status: Optional[str] = None
    data: Optional[Data7] = None


class Transcoding6(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media6(BaseModel):
    transcodings: Optional[List[Transcoding6]] = None


class Data8(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media6] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1907097392(BaseModel):
    status: Optional[str] = None
    data: Optional[Data8] = None


class PublisherMetadata7(BaseModel):
    id: Optional[int] = None
    urn: Optional[str] = None
    artist: Optional[str] = None
    contains_music: Optional[bool] = None
    isrc: Optional[str] = None
    explicit: Optional[bool] = None


class Transcoding7(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media7(BaseModel):
    transcodings: Optional[List[Transcoding7]] = None


class Data9(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: Optional[str] = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata7] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: Optional[str] = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media7] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1905572510(BaseModel):
    status: Optional[str] = None
    data: Optional[Data9] = None


class PublisherMetadata8(BaseModel):
    id: Optional[int] = None
    urn: Optional[str] = None
    contains_music: Optional[bool] = None


class Transcoding8(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media8(BaseModel):
    transcodings: Optional[List[Transcoding8]] = None


class Data10(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata8] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media8] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1902351210(BaseModel):
    status: Optional[str] = None
    data: Optional[Data10] = None


class Transcoding9(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media9(BaseModel):
    transcodings: Optional[List[Transcoding9]] = None


class Data11(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata8] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media9] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1897922193(BaseModel):
    status: Optional[str] = None
    data: Optional[Data11] = None


class PublisherMetadata10(BaseModel):
    id: Optional[int] = None
    urn: Optional[str] = None
    artist: Optional[str] = None
    album_title: Optional[str] = None
    contains_music: Optional[bool] = None
    upc_or_ean: Optional[str] = None
    isrc: Optional[str] = None
    explicit: Optional[bool] = None
    p_line: Optional[str] = None
    p_line_for_display: Optional[str] = None
    c_line: Optional[str] = None
    c_line_for_display: Optional[str] = None
    release_title: Optional[str] = None


class Transcoding10(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media10(BaseModel):
    transcodings: Optional[List[Transcoding10]] = None


class Data12(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: None = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: Optional[str] = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata10] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: Optional[str] = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media10] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1349048875(BaseModel):
    status: Optional[str] = None
    data: Optional[Data12] = None


class Transcoding11(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media11(BaseModel):
    transcodings: Optional[List[Transcoding11]] = None


class Data13(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: None = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: Optional[str] = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata10] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: Optional[str] = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media11] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1428326731(BaseModel):
    status: Optional[str] = None
    data: Optional[Data13] = None


class PublisherMetadata12(BaseModel):
    id: Optional[int] = None
    urn: Optional[str] = None
    artist: Optional[str] = None
    album_title: Optional[str] = None
    contains_music: Optional[bool] = None
    upc_or_ean: Optional[str] = None
    isrc: Optional[str] = None
    explicit: Optional[bool] = None
    p_line: Optional[str] = None
    p_line_for_display: Optional[str] = None
    c_line: Optional[str] = None
    c_line_for_display: Optional[str] = None
    writer_composer: Optional[str] = None
    release_title: Optional[str] = None


class Transcoding12(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media12(BaseModel):
    transcodings: Optional[List[Transcoding12]] = None


class Data14(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: Optional[str] = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata12] = None
    purchase_title: None = None
    purchase_url: Optional[str] = None
    release_date: Optional[str] = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media12] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1726045359(BaseModel):
    status: Optional[str] = None
    data: Optional[Data14] = None


class PublisherMetadata13(BaseModel):
    id: Optional[int] = None
    urn: Optional[str] = None
    artist: Optional[str] = None
    contains_music: Optional[bool] = None
    isrc: Optional[str] = None
    explicit: Optional[bool] = None


class Transcoding13(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media13(BaseModel):
    transcodings: Optional[List[Transcoding13]] = None


class Data15(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata13] = None
    purchase_title: None = None
    purchase_url: Optional[str] = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media13] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1810283730(BaseModel):
    status: Optional[str] = None
    data: Optional[Data15] = None


class PublisherMetadata14(BaseModel):
    id: Optional[int] = None
    urn: Optional[str] = None
    contains_music: Optional[bool] = None


class Transcoding14(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media14(BaseModel):
    transcodings: Optional[List[Transcoding14]] = None


class Data16(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata14] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media14] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1776576804(BaseModel):
    status: Optional[str] = None
    data: Optional[Data16] = None


class Transcoding15(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media15(BaseModel):
    transcodings: Optional[List[Transcoding15]] = None


class Data17(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata14] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media15] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1576590122(BaseModel):
    status: Optional[str] = None
    data: Optional[Data17] = None


class Transcoding16(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media16(BaseModel):
    transcodings: Optional[List[Transcoding16]] = None


class Data18(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata14] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media16] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1671738708(BaseModel):
    status: Optional[str] = None
    data: Optional[Data18] = None


class Transcoding17(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media17(BaseModel):
    transcodings: Optional[List[Transcoding17]] = None


class Data19(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata14] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media17] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1524610999(BaseModel):
    status: Optional[str] = None
    data: Optional[Data19] = None


class Transcoding18(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media18(BaseModel):
    transcodings: Optional[List[Transcoding18]] = None


class Data20(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata14] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media18] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1461141409(BaseModel):
    status: Optional[str] = None
    data: Optional[Data20] = None


class Transcoding19(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media19(BaseModel):
    transcodings: Optional[List[Transcoding19]] = None


class Data21(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata14] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media19] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1875229911(BaseModel):
    status: Optional[str] = None
    data: Optional[Data21] = None


class Transcoding20(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media20(BaseModel):
    transcodings: Optional[List[Transcoding20]] = None


class Data22(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata14] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media20] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1892683068(BaseModel):
    status: Optional[str] = None
    data: Optional[Data22] = None


class PublisherMetadata21(BaseModel):
    id: Optional[int] = None
    urn: Optional[str] = None
    artist: Optional[str] = None
    album_title: Optional[str] = None
    contains_music: Optional[bool] = None
    upc_or_ean: Optional[str] = None
    isrc: Optional[str] = None
    explicit: Optional[bool] = None
    p_line: Optional[str] = None
    p_line_for_display: Optional[str] = None
    c_line: Optional[str] = None
    c_line_for_display: Optional[str] = None
    release_title: Optional[str] = None


class Transcoding21(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media21(BaseModel):
    transcodings: Optional[List[Transcoding21]] = None


class Data23(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: None = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: Optional[str] = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata21] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: Optional[str] = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media21] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1454664049(BaseModel):
    status: Optional[str] = None
    data: Optional[Data23] = None


class PublisherMetadata22(BaseModel):
    id: Optional[int] = None
    urn: Optional[str] = None
    contains_music: Optional[bool] = None


class Transcoding22(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media22(BaseModel):
    transcodings: Optional[List[Transcoding22]] = None


class Data24(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata22] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media22] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1880677728(BaseModel):
    status: Optional[str] = None
    data: Optional[Data24] = None


class Transcoding23(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media23(BaseModel):
    transcodings: Optional[List[Transcoding23]] = None


class Data25(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata22] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media23] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1887457053(BaseModel):
    status: Optional[str] = None
    data: Optional[Data25] = None


class Transcoding24(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media24(BaseModel):
    transcodings: Optional[List[Transcoding24]] = None


class Data26(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata22] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media24] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1652861838(BaseModel):
    status: Optional[str] = None
    data: Optional[Data26] = None


class Transcoding25(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media25(BaseModel):
    transcodings: Optional[List[Transcoding25]] = None


class Data27(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata22] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media25] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1869333657(BaseModel):
    status: Optional[str] = None
    data: Optional[Data27] = None


class Transcoding26(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media26(BaseModel):
    transcodings: Optional[List[Transcoding26]] = None


class Data28(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata22] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media26] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1557605659(BaseModel):
    status: Optional[str] = None
    data: Optional[Data28] = None


class Transcoding27(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media27(BaseModel):
    transcodings: Optional[List[Transcoding27]] = None


class Data29(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata22] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media27] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1420061899(BaseModel):
    status: Optional[str] = None
    data: Optional[Data29] = None


class Transcoding28(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media28(BaseModel):
    transcodings: Optional[List[Transcoding28]] = None


class Data30(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: Optional[str] = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: None = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata22] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: None = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media28] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks(BaseModel):
    status: Optional[str] = None
    data: Optional[Data30] = None


class PublisherMetadata29(BaseModel):
    id: Optional[int] = None
    urn: Optional[str] = None
    artist: Optional[str] = None
    album_title: Optional[str] = None
    contains_music: Optional[bool] = None
    upc_or_ean: Optional[str] = None
    isrc: Optional[str] = None
    explicit: Optional[bool] = None
    p_line: Optional[str] = None
    p_line_for_display: Optional[str] = None
    c_line: Optional[str] = None
    c_line_for_display: Optional[str] = None
    release_title: Optional[str] = None


class Transcoding29(BaseModel):
    url: Optional[str] = None
    preset: Optional[str] = None
    duration: Optional[int] = None
    snipped: Optional[bool] = None
    format: Optional[Format] = None
    quality: Optional[str] = None


class Media29(BaseModel):
    transcodings: Optional[List[Transcoding29]] = None


class Data31(BaseModel):
    artwork_url: Optional[str] = None
    caption: None = None
    commentable: Optional[bool] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    description: None = None
    downloadable: Optional[bool] = None
    download_count: Optional[int] = None
    duration: Optional[int] = None
    full_duration: Optional[int] = None
    embeddable_by: Optional[str] = None
    genre: Optional[str] = None
    has_downloads_left: Optional[bool] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    label_name: Optional[str] = None
    last_modified: Optional[str] = None
    license: Optional[str] = None
    likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playback_count: Optional[int] = None
    public: Optional[bool] = None
    publisher_metadata: Optional[PublisherMetadata29] = None
    purchase_title: None = None
    purchase_url: None = None
    release_date: Optional[str] = None
    reposts_count: Optional[int] = None
    secret_token: None = None
    sharing: Optional[str] = None
    state: Optional[str] = None
    streamable: Optional[bool] = None
    title: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    user_id: Optional[int] = None
    visuals: None = None
    display_date: Optional[str] = None
    media: Optional[Media29] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    track_authorization: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    user: Optional[str] = None
    waveformKey: Optional[str] = None
    tags: Optional[List[str]] = None
    dataRepresentation: Optional[int] = None
    category: Optional[str] = None


class SoundcloudTracks1605624648(BaseModel):
    status: Optional[str] = None
    data: Optional[Data31] = None


class Data32(BaseModel):
    id: Optional[int] = None
    kind: Optional[str] = None
    monetization_model: Optional[str] = None
    policy: Optional[str] = None
    dataRepresentation: Optional[int] = None


class SoundcloudTracks1532283679(BaseModel):
    status: Optional[str] = None
    data: Optional[Data32] = None


class SoundcloudTracks1517412253(BaseModel):
    status: Optional[str] = None
    data: Optional[Data32] = None


class SoundcloudTracks1497314884(BaseModel):
    status: Optional[str] = None
    data: Optional[Data32] = None


class Product(BaseModel):
    id: Optional[str] = None


class CreatorSubscription(BaseModel):
    product: Optional[Product] = None


class CreatorSubscription1(BaseModel):
    product: Optional[Product] = None


class Visual(BaseModel):
    urn: Optional[str] = None
    entry_time: Optional[int] = None
    visual_url: Optional[str] = None


class Visuals(BaseModel):
    urn: Optional[str] = None
    enabled: Optional[bool] = None
    visuals: Optional[List[Visual]] = None
    tracking: None = None


class Badges(BaseModel):
    pro: Optional[bool] = None
    creator_mid_tier: Optional[bool] = None
    pro_unlimited: Optional[bool] = None
    verified: Optional[bool] = None


class Data35(BaseModel):
    avatar_url: Optional[str] = None
    city: Optional[str] = None
    comments_count: Optional[int] = None
    country_code: Optional[str] = None
    created_at: Optional[str] = None
    creator_subscriptions: Optional[List[CreatorSubscription]] = None
    creator_subscription: Optional[CreatorSubscription1] = None
    description: Optional[str] = None
    followers_count: Optional[int] = None
    followings_count: Optional[int] = None
    first_name: Optional[str] = None
    full_name: Optional[str] = None
    groups_count: Optional[int] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    last_modified: Optional[str] = None
    last_name: Optional[str] = None
    likes_count: Optional[int] = None
    playlist_likes_count: Optional[int] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    playlist_count: Optional[int] = None
    reposts_count: None = None
    track_count: Optional[int] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    username: Optional[str] = None
    verified: Optional[bool] = None
    visuals: Optional[Visuals] = None
    badges: Optional[Badges] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    dataRepresentation: Optional[int] = None


class Data36(BaseModel):
    avatar_url: Optional[str] = None
    first_name: Optional[str] = None
    followers_count: Optional[int] = None
    full_name: Optional[str] = None
    id: Optional[int] = None
    kind: Optional[str] = None
    last_modified: Optional[str] = None
    last_name: Optional[str] = None
    permalink: Optional[str] = None
    permalink_url: Optional[str] = None
    uri: Optional[str] = None
    urn: Optional[str] = None
    username: Optional[str] = None
    verified: Optional[bool] = None
    city: Optional[str] = None
    country_code: Optional[str] = None
    badges: Optional[Badges] = None
    station_urn: Optional[str] = None
    station_permalink: Optional[str] = None
    dataRepresentation: Optional[int] = None


class Data37(BaseModel):
    collection: Optional[List[str]] = None
    next_href: Optional[str] = None
    query_urn: None = None
    id: Optional[str] = None
    fetchingMore: Optional[bool] = None


class SoundcloudUsers(BaseModel):
    status: Optional[str] = None
    data: Optional[Data37] = None


class Data38(BaseModel):
    collection: Optional[List[str]] = None
    next_href: None = None
    query_urn: None = None
    id: Optional[str] = None
    fetchingMore: Optional[bool] = None


class CollectionItem(BaseModel):
    id: Optional[str] = None
    schema_: Optional[str] = Field(None, alias="schema")


class Data39(BaseModel):
    collection: Optional[List[CollectionItem]] = None
    next_href: None = None
    query_urn: None = None
    id: Optional[str] = None
    fetchingMore: Optional[bool] = None


class Entities(BaseModel):
    playlists: Optional[Playlists] = None
    systemPlaylists: Optional[Dict[str, Any]] = None
    tracks: Optional[Dict[str, Data]] = None
    relatedTracksCollections: Optional[Dict[str, Any]] = None
    users: Optional[Dict[str, SoundCloudUser]] = None
    webProfiles: Optional[Dict[str, Any]] = None
    comments: Optional[Dict[str, Any]] = None
    reposts: Optional[Dict[str, Any]] = None
    chartsCollections: Optional[Dict[str, Any]] = None
    featuredTracksCollections: Optional[Dict[str, Any]] = None
    tracksCollections: Optional[Dict[str, Data]] = None
    topTracksCollections: Optional[Dict[str, Data]] = None
    playlistsCollections: Optional[Dict[str, Any]] = None
    anyPlaylistsCollections: Optional[Dict[str, Any]] = None
    playlistLikersCollections: Optional[Dict[str, Any]] = None
    playlistRepostersCollections: Optional[Dict[str, Any]] = None
    followersCollections: Optional[Dict[str, Any]] = None
    followingsCollections: Optional[Dict[str, Any]] = None
    waveformData: Optional[Dict[str, Any]] = None
    searchQueriesCollections: Optional[Dict[str, Any]] = None
    searchResultsCollections: Optional[Dict[str, Any]] = None
    tagsCollections: Optional[Dict[str, Any]] = None
    spotlightCollections: Optional[Dict[str, Data]] = None
    likesCollections: Optional[Dict[str, Any]] = None
    commentsCollections: Optional[Dict[str, Any]] = None
    trackLikersCollections: Optional[Dict[str, Any]] = None
    trackRepostersCollections: Optional[Dict[str, Any]] = None
    repostsCollections: Optional[Dict[str, Any]] = None
    streamCollections: Optional[Dict[str, Any]] = None
    trackPlaylistsCollections: Optional[Dict[str, Any]] = None
    trackAlbumsCollections: Optional[Dict[str, Any]] = None
    albumsCollections: Optional[Dict[str, Any]] = None
    relatedUsersCollections: Optional[Dict[str, Any]] = None
    discoverCollections: Optional[Dict[str, Any]] = None
    mixedSelectionsCollections: Optional[Dict[str, Any]] = None
    whoToFollowCollections: Optional[Dict[str, Any]] = None
    historicalPlayContexts: Optional[Dict[str, Any]] = None
    playHistoryContextCollections: Optional[Dict[str, Any]] = None
    historicalPlays: Optional[Dict[str, Any]] = None
    playHistoryCollections: Optional[Dict[str, Any]] = None


class MeUserUrn(BaseModel):
    status: Optional[str] = None


class Authentication(BaseModel):
    meUserUrn: Optional[MeUserUrn] = None


class SoundcloudUsersAnonymous(BaseModel):
    status: Optional[str] = None
    data: Optional[Dict[str, Any]] = None


class Followings(BaseModel):
    soundcloud_users_anonymous: Optional[SoundcloudUsersAnonymous] = Field(
        None, alias="soundcloud:users:anonymous"
    )


class TrackLikes(BaseModel):
    soundcloud_users_anonymous: Optional[SoundcloudUsersAnonymous] = Field(
        None, alias="soundcloud:users:anonymous"
    )


class TrackReposts(BaseModel):
    soundcloud_users_anonymous: Optional[SoundcloudUsersAnonymous] = Field(
        None, alias="soundcloud:users:anonymous"
    )


class PlaylistLikes(BaseModel):
    soundcloud_users_anonymous: Optional[SoundcloudUsersAnonymous] = Field(
        None, alias="soundcloud:users:anonymous"
    )


class PlaylistReposts(BaseModel):
    soundcloud_users_anonymous: Optional[SoundcloudUsersAnonymous] = Field(
        None, alias="soundcloud:users:anonymous"
    )


class Toggles(BaseModel):
    followings: Optional[Followings] = None
    trackLikes: Optional[TrackLikes] = None
    trackReposts: Optional[TrackReposts] = None
    playlistLikes: Optional[PlaylistLikes] = None
    playlistReposts: Optional[PlaylistReposts] = None


class InitialStoreState(BaseModel):
    entities: Optional[Entities] = None
    entityUrlMap: Optional[Dict[str, Any]] = None
    authentication: Optional[Authentication] = None
    toggles: Optional[Toggles] = None


class PageProps(BaseModel):
    userUrn: Optional[str] = None
    pageInfo: Optional[PageInfo] = None
    initialStoreState: Optional[InitialStoreState] = None


class GeoInfo(BaseModel):
    country_code: Optional[str] = None
    country_name: Optional[str] = None
    region: Optional[str] = None
    city: Optional[str] = None
    postal_code: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None


class BrowsingEnv(BaseModel):
    geoInfo: Optional[GeoInfo] = None
    referrer: Optional[str] = None
    device: Optional[str] = None
    browser: Optional[str] = None


class Props(BaseModel):
    pageProps: Optional[PageProps] = None
    anonymousId: Optional[str] = None
    browserTabId: Optional[str] = None
    initialLocale: Optional[str] = None
    initialPhrases: None = None
    initialFeatures: Optional[List[str]] = None
    experiments: Optional[List] = None
    forcedFeatures: Optional[List] = None
    browsingEnv: Optional[BrowsingEnv] = None
    isErrorReportingEnabled: Optional[bool] = None


class Query(BaseModel):
    user: Optional[str] = None


class RuntimeConfig(BaseModel):
    env: Optional[str] = None
    isDev: Optional[bool] = None
    host: Optional[str] = None
    port: Optional[str] = None
    stagingId: Optional[str] = None
    clientId: Optional[str] = None
    appId: Optional[str] = None
    buildVersion: Optional[str] = None
    apiWebHost: Optional[str] = None
    apiAuthHost: Optional[str] = None
    secureHost: Optional[str] = None
    apiFlowHost: Optional[str] = None
    peopleDirectoryHost: Optional[str] = None
    staticPagesHost: Optional[str] = None
    moEngageApiKey: Optional[str] = None
    wisHost: Optional[str] = None
    v2Host: Optional[str] = None
    authUiHost: Optional[str] = None
    webAuthUseTestCaptcha: Optional[bool] = None
    firebaseApiKey: Optional[str] = None
    oauthRedirectUri: Optional[str] = None
    frameAncestors: Optional[str] = None
    datadomeClientApiKey: Optional[str] = None
    isAirbrakeEnabled: Optional[str] = None
    airbrakeProjectId: Optional[str] = None
    airbrakeProjectKey: Optional[str] = None
    airbrakeSampleRate: Optional[str] = None
    zendeskHost: Optional[str] = None
    drmLicenseUri: Optional[str] = None
    shouldUseSrv: Optional[bool] = None
    fetchTimeoutRetryMs: Optional[int] = None


class DangerouslySetInnerHTML(BaseModel):
    field__html: Optional[str] = Field(None, alias="__html")


class Head(BaseModel):
    charSet: Optional[str] = None
    src: Optional[str] = None
    async_: Optional[bool] = Field(None, alias="async")
    dangerouslySetInnerHTML: Optional[DangerouslySetInnerHTML] = None
    type: Optional[str] = None
    data_domain_script: Optional[str] = Field(None, alias="data-domain-script")
    data_testid: Optional[str] = Field(None, alias="data-testid")
    rel: Optional[str] = None
    sizes: Optional[str] = None
    href: Optional[str] = None
    title: Optional[str] = None
    property: Optional[str] = None
    content: Optional[str] = None
    children: Optional[str] = None
    name: Optional[str] = None
    as_: Optional[str] = Field(None, alias="as")


class SoundCloudUser(BaseModel):
    props: Optional[Props] = None
    page: Optional[str] = None
    query: Optional[Query] = None
    buildId: Optional[str] = None
    assetPrefix: Optional[str] = None
    runtimeConfig: Optional[RuntimeConfig] = None
    isFallback: Optional[bool] = None
    customServer: Optional[bool] = None
    gip: Optional[bool] = None
    appGip: Optional[bool] = None
    head: Optional[List[List[Union[str, Head]]]] = None
