# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2025-01-07T21:18:21+00:00

from __future__ import annotations
import json
from bs4 import BeautifulSoup
from typing import List, Optional
from playwright.async_api import async_playwright
from pydantic import BaseModel, Field


class ViewerInfo(BaseModel):
    country: Optional[str] = None
    locale: Optional[str] = None
    isGdprCountry: Optional[bool] = None


class Localization(BaseModel):
    direction: Optional[int] = None


class OneLinkParams(BaseModel):
    oneLinkBaseUrl: Optional[str] = None
    pidKeys: Optional[List[str]] = None
    pidFallbackValue: Optional[str] = None
    campaignKeys: Optional[List[str]] = None
    campaignFallbackValue: Optional[str] = None
    googleClickIdParam: Optional[str] = None
    deepLinkUrl: Optional[str] = None
    iosAppStoreUrl: Optional[str] = None
    desktopPageUrl: Optional[str] = None


class PageLinks(BaseModel):
    oneLinkUrl: Optional[str] = None
    snapchatCanonicalUrl: Optional[str] = None
    canonicalUrl: Optional[str] = None
    snapcodeImageUrl: Optional[str] = None
    downloadUrl: Optional[str] = None
    oneLinkParams: Optional[OneLinkParams] = None
    snapchatDeepLinkUrl: Optional[str] = None


class PageDescription(BaseModel):
    value: Optional[str] = None


class PageMetadata(BaseModel):
    pageType: Optional[int] = None
    pageTitle: Optional[str] = None
    pageDescription: Optional[PageDescription] = None
    shareId: Optional[str] = None


class PublicProfileInfo1(BaseModel):
    username: Optional[str] = None
    title: Optional[str] = None
    snapcodeImageUrl: Optional[str] = None
    badge: Optional[int] = None
    categoryStringId: Optional[str] = None
    subcategoryStringId: Optional[str] = None
    subscriberCount: Optional[str] = None
    bio: Optional[str] = None
    websiteUrl: Optional[str] = None
    profilePictureUrl: Optional[str] = None
    address: Optional[str] = None
    hasCuratedHighlights: Optional[bool] = None
    hasSpotlightHighlights: Optional[bool] = None
    mutableName: Optional[str] = None
    publisherType: Optional[str] = None
    squareHeroImageUrl: Optional[str] = None
    primaryColor: Optional[str] = None
    hasStory: Optional[bool] = None
    relatedAccountsInfo: Optional[List] = None


class SubscribeLink(BaseModel):
    oneLinkBaseUrl: Optional[str] = None
    pidKeys: Optional[List[str]] = None
    pidFallbackValue: Optional[str] = None
    campaignKeys: Optional[List[str]] = None
    campaignFallbackValue: Optional[str] = None
    googleClickIdParam: Optional[str] = None
    deepLinkUrl: Optional[str] = None
    iosAppStoreUrl: Optional[str] = None
    desktopPageUrl: Optional[str] = None


class RelatedAccountsInfoItem(BaseModel):
    publicProfileInfo: Optional[PublicProfileInfo1] = None
    subscribeLink: Optional[SubscribeLink] = None


class CreationTimestampMs(BaseModel):
    value: Optional[str] = None


class LastUpdateTimestampMs(BaseModel):
    value: Optional[str] = None


class PublicProfileInfo(BaseModel):
    username: Optional[str] = None
    title: Optional[str] = None
    snapcodeImageUrl: Optional[str] = None
    badge: Optional[int] = None
    categoryStringId: Optional[str] = None
    subcategoryStringId: Optional[str] = None
    subscriberCount: Optional[int] = None
    bio: Optional[str] = None
    websiteUrl: Optional[str] = None
    profilePictureUrl: Optional[str] = None
    address: Optional[str] = None
    hasCuratedHighlights: Optional[bool] = None
    hasSpotlightHighlights: Optional[bool] = None
    mutableName: Optional[str] = None
    publisherType: Optional[str] = None
    squareHeroImageUrl: Optional[str] = None
    primaryColor: Optional[str] = None
    hasStory: Optional[bool] = None
    relatedAccountsInfo: Optional[List[RelatedAccountsInfoItem]] = None
    creationTimestampMs: Optional[CreationTimestampMs] = None
    lastUpdateTimestampMs: Optional[LastUpdateTimestampMs] = None


class UserProfile(BaseModel):
    field_case: Optional[str] = Field(None, alias="$case")
    publicProfileInfo: Optional[PublicProfileInfo] = None


class SnapId(BaseModel):
    value: Optional[str] = None


class MediaPreviewUrl(BaseModel):
    value: Optional[str] = None


class SnapUrls(BaseModel):
    mediaUrl: Optional[str] = None
    mediaPreviewUrl: Optional[MediaPreviewUrl] = None


class TimestampInSec(BaseModel):
    value: Optional[str] = None


class SnapListItem(BaseModel):
    snapIndex: Optional[int] = None
    snapId: Optional[SnapId] = None
    snapMediaType: Optional[int] = None
    snapUrls: Optional[SnapUrls] = None
    timestampInSec: Optional[TimestampInSec] = None


class StoryId(BaseModel):
    value: Optional[str] = None


class ThumbnailUrl(BaseModel):
    value: Optional[str] = None


class Story(BaseModel):
    storyType: Optional[int] = None
    snapList: Optional[List[SnapListItem]] = None
    storyId: Optional[StoryId] = None
    thumbnailUrl: Optional[ThumbnailUrl] = None
    storyTapId: Optional[str] = None


class Size(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None


class TwitterImage(BaseModel):
    url: Optional[str] = None
    size: Optional[Size] = None


class FacebookImage(BaseModel):
    url: Optional[str] = None
    size: Optional[Size] = None


class LinkPreview(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    canonicalUrl: Optional[str] = None
    twitterImage: Optional[TwitterImage] = None
    facebookImage: Optional[FacebookImage] = None


class SnapUrls1(BaseModel):
    mediaUrl: Optional[str] = None
    mediaPreviewUrl: Optional[MediaPreviewUrl] = None


class SnapListItem1(BaseModel):
    snapIndex: Optional[int] = None
    snapId: Optional[SnapId] = None
    snapMediaType: Optional[int] = None
    snapUrls: Optional[SnapUrls1] = None
    timestampInSec: Optional[TimestampInSec] = None


class StoryTitle(BaseModel):
    value: Optional[str] = None


class HighlightId(BaseModel):
    value: Optional[str] = None


class SpotlightHighlight(BaseModel):
    storyType: Optional[int] = None
    snapList: Optional[List[SnapListItem1]] = None
    storyId: Optional[StoryId] = None
    storyTitle: Optional[StoryTitle] = None
    thumbnailUrl: Optional[ThumbnailUrl] = None
    storyTapId: Optional[str] = None
    highlightId: Optional[HighlightId] = None


class PersonCreator(BaseModel):
    username: Optional[str] = None
    url: Optional[str] = None
    name: Optional[str] = None


class Creator(BaseModel):
    field_case: Optional[str] = Field(None, alias="$case")
    personCreator: Optional[PersonCreator] = None


class VideoMetadata(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    thumbnailUrl: Optional[str] = None
    uploadDateMs: Optional[str] = None
    viewCount: Optional[str] = None
    contentUrl: Optional[str] = None
    creator: Optional[Creator] = None
    durationMs: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    keywords: Optional[List] = None
    shareCount: Optional[str] = None
    embeddedTextCaption: Optional[str] = None


class ContextCard(BaseModel):
    contextType: Optional[int] = None
    title: Optional[str] = None
    subtitle: Optional[str] = None
    url: Optional[str] = None
    thumbnailUrl: Optional[str] = None
    snapcodeUrl: Optional[str] = None
    thumbnailType: Optional[int] = None
    hasBadge: Optional[bool] = None


class EngagementStats(BaseModel):
    viewCount: Optional[str] = None
    shareCount: Optional[str] = None


class SpotlightStoryMetadatum(BaseModel):
    videoMetadata: Optional[VideoMetadata] = None
    hashtags: Optional[List[str]] = None
    contextCards: Optional[List[ContextCard]] = None
    engagementStats: Optional[EngagementStats] = None
    deeplink: Optional[str] = None
    oneLinkParams: Optional[OneLinkParams] = None
    description: Optional[str] = None


class Gaid(BaseModel):
    UAId: Optional[str] = None
    measurementId: Optional[str] = None


class Messages(BaseModel):
    field_9d_q7: Optional[str] = Field(None, alias="+9d+q7")
    field_ByJA_: Optional[str] = Field(None, alias="+ByJA/")
    field_hwkQQ: Optional[str] = Field(None, alias="+hwkQQ")
    field_SYKuN: Optional[str] = Field(None, alias="/SYKuN")
    field_06XEyj: Optional[str] = Field(None, alias="06XEyj")
    field_0Y6c0W: Optional[str] = Field(None, alias="0Y6c0W")
    field_0YKDxr: Optional[str] = Field(None, alias="0YKDxr")
    field_1V8Uma: Optional[str] = Field(None, alias="1V8Uma")
    field_1egAGi: Optional[str] = Field(None, alias="1egAGi")
    field_1kdcl2: Optional[str] = Field(None, alias="1kdcl2")
    field_24ARrW: Optional[str] = Field(None, alias="24ARrW")
    field_2l730k: Optional[str] = Field(None, alias="2l730k")
    field_3a7j8_: Optional[str] = Field(None, alias="3a7j8/")
    field_4_lFm_: Optional[str] = Field(None, alias="4+lFm/")
    field_4rgvx7: Optional[str] = Field(None, alias="4rgvx7")
    field_5oTzR_: Optional[str] = Field(None, alias="5oTzR/")
    field_5v6wP7: Optional[str] = Field(None, alias="5v6wP7")
    field_5zZGnG: Optional[str] = Field(None, alias="5zZGnG")
    field_7BHw3h: Optional[str] = Field(None, alias="7BHw3h")
    field_7HP0Jf: Optional[str] = Field(None, alias="7HP0Jf")
    field_7XZM2L: Optional[str] = Field(None, alias="7XZM2L")
    field_7rVnIj: Optional[str] = Field(None, alias="7rVnIj")
    field_7xehRy: Optional[str] = Field(None, alias="7xehRy")
    field_7yuYaU: Optional[str] = Field(None, alias="7yuYaU")
    field_97lfct: Optional[str] = Field(None, alias="97lfct")
    CJBFGo: Optional[str] = None
    CVucIf: Optional[str] = None
    DY4yHA: Optional[str] = None
    Ddp4_3: Optional[str] = Field(None, alias="Ddp4+3")
    EPBE_l: Optional[str] = Field(None, alias="EPBE+l")
    FbeKso: Optional[str] = None
    Fsg136: Optional[str] = None
    Gh1a_j: Optional[str] = Field(None, alias="Gh1a/j")
    GssbOn: Optional[str] = None
    HVgZaB: Optional[str] = None
    I6sovq: Optional[str] = None
    IWKERN: Optional[str] = None
    JHt_mt: Optional[str] = Field(None, alias="JHt/mt")
    Ju77ns: Optional[str] = None
    LLCXk7: Optional[str] = None
    MDthgV: Optional[str] = None
    NXPVkv: Optional[str] = None
    NrbjlZ: Optional[str] = None
    OKhRC6: Optional[str] = None
    PQcLi_: Optional[str] = Field(None, alias="PQcLi/")
    Q6xlJQ: Optional[str] = None
    Q71IbU: Optional[str] = None
    QQ9g7q: Optional[str] = None
    Qr4Ehq: Optional[str] = None
    RmE5lP: Optional[str] = None
    RotAJ1: Optional[str] = None
    RtNy71: Optional[str] = None
    SCe4GQ: Optional[str] = None
    SVOJKh: Optional[str] = None
    T482Xy: Optional[str] = None
    T7NeMu: Optional[str] = None
    TNK_W_: Optional[str] = Field(None, alias="TNK/W/")
    Uk55sM: Optional[str] = None
    VejKVU: Optional[str] = None
    WGtpBM: Optional[str] = None
    XbXoMR: Optional[str] = None
    ZPrHrl: Optional[str] = None
    ZViZgq: Optional[str] = None
    ZlJO0Q: Optional[str] = None
    Zv3qzk: Optional[str] = None
    aSXQy0: Optional[str] = None
    ah6l3c: Optional[str] = None
    ais8eK: Optional[str] = None
    by2dgE: Optional[str] = None
    dAksd9: Optional[str] = None
    dItw6q: Optional[str] = None
    dJDu_3: Optional[str] = Field(None, alias="dJDu/3")
    dPJhtZ: Optional[str] = None
    dkWyPr: Optional[str] = None
    eyF_XC: Optional[str] = Field(None, alias="eyF+XC")
    fPIy5v: Optional[str] = None
    ge04bU: Optional[str] = None
    hPxDQC: Optional[str] = None
    hldPiC: Optional[str] = None
    jWa4OT: Optional[str] = None
    kNCf90: Optional[str] = None
    ksNund: Optional[str] = None
    l1fnUG: Optional[str] = None
    l88c7e: Optional[str] = None
    m9YeNS: Optional[str] = None
    mkg4Jx: Optional[str] = None
    pCK8FJ: Optional[str] = None
    pPIiOl: Optional[str] = None
    qjJvue: Optional[str] = None
    qszDvG: Optional[str] = None
    rKMlss: Optional[str] = None
    rL8HYz: Optional[str] = None
    s2XNWr: Optional[str] = None
    sbYi0B: Optional[str] = None
    snUFAy: Optional[str] = None
    tZtw7V: Optional[str] = None
    vqdER6: Optional[str] = None
    wBWCyR: Optional[str] = None
    wVfxbD: Optional[str] = None
    wpLx7z: Optional[str] = None
    x1C_5K: Optional[str] = Field(None, alias="x1C/5K")
    xLaO8v: Optional[str] = None
    yGAZt3: Optional[str] = None
    yR5xHa: Optional[str] = None
    ydFYny: Optional[str] = None
    ys7Y26: Optional[str] = None
    zExXNB: Optional[str] = None
    zFRQEo: Optional[str] = None
    W7Hu1E: Optional[str] = None
    bd9vjd: Optional[str] = None
    ciBJVK: Optional[str] = None
    kZW3hz: Optional[str] = None
    tblBgp: Optional[str] = None
    tmrBgq: Optional[str] = None
    field_15sbQK: Optional[str] = Field(None, alias="15sbQK")
    field_1JAbNA: Optional[str] = Field(None, alias="1JAbNA")
    field_1TqZE7: Optional[str] = Field(None, alias="1TqZE7")
    field_2dg3bf: Optional[str] = Field(None, alias="2dg3bf")
    field_2iEYAu: Optional[str] = Field(None, alias="2iEYAu")
    field_4fh4h: Optional[str] = Field(None, alias="4fh4h")
    field_4igqPT: Optional[str] = Field(None, alias="4igqPT")
    field_5lirL_: Optional[str] = Field(None, alias="5lirL/")
    field_67xqDn: Optional[str] = Field(None, alias="67xqDn")
    field_7cBPZM: Optional[str] = Field(None, alias="7cBPZM")
    field_9VdhT5: Optional[str] = Field(None, alias="9VdhT5")
    AiOf_Y: Optional[str] = Field(None, alias="AiOf/Y")
    BhoFmY: Optional[str] = None
    CxMU6U: Optional[str] = None
    DYQj9E: Optional[str] = None
    FobC0E: Optional[str] = None
    H2xi8I: Optional[str] = None
    I0Yym4: Optional[str] = None
    JJQ8_E: Optional[str] = Field(None, alias="JJQ8/E")
    Ja6NcZ: Optional[str] = None
    LITyBO: Optional[str] = None
    LWQk4A: Optional[str] = None
    LXGd0Z: Optional[str] = None
    MPfmoz: Optional[str] = None
    MRRwTC: Optional[str] = None
    NaulaK: Optional[str] = None
    OYcx_R: Optional[str] = Field(None, alias="OYcx+R")
    PLjvWf: Optional[str] = None
    QLSvWU: Optional[str] = None
    T1q_tQ: Optional[str] = Field(None, alias="T1q+tQ")
    TU8E7s: Optional[str] = None
    ULCvDn: Optional[str] = None
    UrD_sz: Optional[str] = Field(None, alias="UrD/sz")
    VtHN3Y: Optional[str] = None
    W_80Oc: Optional[str] = Field(None, alias="W+80Oc")
    XCDdvu: Optional[str] = None
    Xrm52A: Optional[str] = None
    YYQ8_E: Optional[str] = Field(None, alias="YYQ8/E")
    ZC0P9H: Optional[str] = None
    bfdn8: Optional[str] = None
    cdFMt7: Optional[str] = None
    d1Fnt_: Optional[str] = Field(None, alias="d1Fnt+")
    dhrOUZ: Optional[str] = None
    dn5evd: Optional[str] = None
    e7wSLn: Optional[str] = None
    fmKLYj: Optional[str] = None
    jsf76: Optional[str] = None
    jta505: Optional[str] = None
    khZ_z6: Optional[str] = Field(None, alias="khZ+z6")
    lH1D9c: Optional[str] = None
    m5EFsX: Optional[str] = None
    mba67t: Optional[str] = None
    milYa0: Optional[str] = None
    nasd8h: Optional[str] = None
    pr9aMR: Optional[str] = None
    qFeyfb: Optional[str] = None
    qhno3L: Optional[str] = None
    rghIM3: Optional[str] = None
    ruWrCp: Optional[str] = None
    rx5d5k: Optional[str] = None
    sbas67: Optional[str] = None
    sdfds6: Optional[str] = None
    sdvsd3: Optional[str] = None
    sjbs88: Optional[str] = None
    tjEfLW: Optional[str] = None
    tqBhfK: Optional[str] = None
    tv_T1h: Optional[str] = Field(None, alias="tv+T1h")
    u6AK3M: Optional[str] = None
    ugwDM5: Optional[str] = None
    vXHzz1: Optional[str] = None
    wvwh5b: Optional[str] = None
    xwvWv3: Optional[str] = None
    ywboC7: Optional[str] = None
    zjVcbH: Optional[str] = None
    field_Im81x: Optional[str] = Field(None, alias="+Im81x")
    field_c9FIk: Optional[str] = Field(None, alias="+c9FIk")
    field_d_tNA: Optional[str] = Field(None, alias="+d/tNA")
    field_hgjwh: Optional[str] = Field(None, alias="+hgjwh")
    field_ieU8R: Optional[str] = Field(None, alias="+ieU8R")
    field_lhElX: Optional[str] = Field(None, alias="+lhElX")
    field_0qKds: Optional[str] = Field(None, alias="/0qKds")
    field_5cdjt: Optional[str] = Field(None, alias="/5cdjt")
    field_9BpZC: Optional[str] = Field(None, alias="/9BpZC")
    field_hi87u: Optional[str] = Field(None, alias="/hi87u")
    field_r7Bc4: Optional[str] = Field(None, alias="/r7Bc4")
    field_uf3l4: Optional[str] = Field(None, alias="/uf3l4")
    field_04qzmG: Optional[str] = Field(None, alias="04qzmG")
    field_0dJz6S: Optional[str] = Field(None, alias="0dJz6S")
    field_0hPPc_: Optional[str] = Field(None, alias="0hPPc+")
    field_0yjej6: Optional[str] = Field(None, alias="0yjej6")
    field_1PLQmO: Optional[str] = Field(None, alias="1PLQmO")
    field_1PzCdm: Optional[str] = Field(None, alias="1PzCdm")
    field_1ROxNo: Optional[str] = Field(None, alias="1ROxNo")
    field_1jMkF_: Optional[str] = Field(None, alias="1jMkF/")
    field_1q_ois: Optional[str] = Field(None, alias="1q/ois")
    field_1vXyK5: Optional[str] = Field(None, alias="1vXyK5")
    field_1xokhb: Optional[str] = Field(None, alias="1xokhb")
    field_2DrFi_: Optional[str] = Field(None, alias="2DrFi/")
    field_2LLiYb: Optional[str] = Field(None, alias="2LLiYb")
    field_2V40yT: Optional[str] = Field(None, alias="2V40yT")
    field_2abiy0: Optional[str] = Field(None, alias="2abiy0")
    field_30Mg5_: Optional[str] = Field(None, alias="30Mg5/")
    field_331fBb: Optional[str] = Field(None, alias="331fBb")
    field_39y4D4: Optional[str] = Field(None, alias="39y4D4")
    field_3Rh_pv: Optional[str] = Field(None, alias="3Rh+pv")
    field_3T2iOg: Optional[str] = Field(None, alias="3T2iOg")
    field_3nkhih: Optional[str] = Field(None, alias="3nkhih")
    field_4_tITf: Optional[str] = Field(None, alias="4+tITf")
    field_4O4dPg: Optional[str] = Field(None, alias="4O4dPg")
    field_4kjIFD: Optional[str] = Field(None, alias="4kjIFD")
    field_4mW6ME: Optional[str] = Field(None, alias="4mW6ME")
    field_4tH4ib: Optional[str] = Field(None, alias="4tH4ib")
    field_5_dpGU: Optional[str] = Field(None, alias="5+dpGU")
    field_52kdGd: Optional[str] = Field(None, alias="52kdGd")
    field_57yuyz: Optional[str] = Field(None, alias="57yuyz")
    field_58SIKu: Optional[str] = Field(None, alias="58SIKu")
    field_5FAe7C: Optional[str] = Field(None, alias="5FAe7C")
    field_5HsSrO: Optional[str] = Field(None, alias="5HsSrO")
    field_5LRsH1: Optional[str] = Field(None, alias="5LRsH1")
    field_5Zsb8t: Optional[str] = Field(None, alias="5Zsb8t")
    field_5m3Hu8: Optional[str] = Field(None, alias="5m3Hu8")
    field_6307RX: Optional[str] = Field(None, alias="6307RX")
    field_67jBS8: Optional[str] = Field(None, alias="67jBS8")
    field_6AXoVq: Optional[str] = Field(None, alias="6AXoVq")
    field_6SzqQV: Optional[str] = Field(None, alias="6SzqQV")
    field_6TiqPJ: Optional[str] = Field(None, alias="6TiqPJ")
    field_6ZgBbw: Optional[str] = Field(None, alias="6ZgBbw")
    field_6qOZYA: Optional[str] = Field(None, alias="6qOZYA")
    field_7_HNiU: Optional[str] = Field(None, alias="7/HNiU")
    field_7HIoTU: Optional[str] = Field(None, alias="7HIoTU")
    field_7Yy0_b: Optional[str] = Field(None, alias="7Yy0+b")
    field_80nWOt: Optional[str] = Field(None, alias="80nWOt")
    field_81kGin: Optional[str] = Field(None, alias="81kGin")
    field_884qo6: Optional[str] = Field(None, alias="884qo6")
    field_8EnWa6: Optional[str] = Field(None, alias="8EnWa6")
    field_8Sw4jY: Optional[str] = Field(None, alias="8Sw4jY")
    field_90h7_c: Optional[str] = Field(None, alias="90h7/c")
    field_9KADbj: Optional[str] = Field(None, alias="9KADbj")
    A_17s3: Optional[str] = Field(None, alias="A+17s3")
    A__js0: Optional[str] = Field(None, alias="A//js0")
    A0QuW0: Optional[str] = None
    ATeDiR: Optional[str] = None
    AbkQPs: Optional[str] = None
    BIR9MS: Optional[str] = None
    BLbe57: Optional[str] = None
    BoKhrr: Optional[str] = None
    Bq2nwA: Optional[str] = None
    ByhIs0: Optional[str] = None
    C_46Vz: Optional[str] = Field(None, alias="C/46Vz")
    CAgCZ5: Optional[str] = None
    Co_5iq: Optional[str] = Field(None, alias="Co/5iq")
    CreatorFollowerCount: Optional[str] = None
    D4A2LZ: Optional[str] = None
    DIFKwk: Optional[str] = None
    DUdaMN: Optional[str] = None
    DYK0ve: Optional[str] = None
    Daodtv: Optional[str] = None
    E902E8: Optional[str] = None
    ECeXar: Optional[str] = None
    EFE6ZV: Optional[str] = None
    ERkh0f: Optional[str] = None
    ESomE8: Optional[str] = None
    EbbVcC: Optional[str] = None
    EfncpL: Optional[str] = None
    Evxi_h: Optional[str] = Field(None, alias="Evxi/h")
    FDOu63: Optional[str] = None
    FN5U0u: Optional[str] = None
    Fohnyv: Optional[str] = None
    FpzDjr: Optional[str] = None
    Ftta6c: Optional[str] = None
    G0CCzJ: Optional[str] = None
    G5CvJf: Optional[str] = None
    GJZs5E: Optional[str] = None
    GL9Msi: Optional[str] = None
    GZDSC0: Optional[str] = None
    Gvuqme: Optional[str] = None
    HLxWNM: Optional[str] = None
    HNQOND: Optional[str] = None
    HkNqjk: Optional[str] = None
    HmnV8f: Optional[str] = None
    HqSThL: Optional[str] = None
    I73NDr: Optional[str] = None
    IC39KF: Optional[str] = None
    IOia3K: Optional[str] = None
    IeYjFw: Optional[str] = None
    IxV_TQ: Optional[str] = Field(None, alias="IxV+TQ")
    JFYhZv: Optional[str] = None
    Jm15g7: Optional[str] = None
    Jnm5JX: Optional[str] = None
    Jo8O9K: Optional[str] = None
    K283wu: Optional[str] = None
    L2hojs: Optional[str] = None
    LDo7Px: Optional[str] = None
    LSP7zt: Optional[str] = None
    LhhU6X: Optional[str] = None
    LnWDDv: Optional[str] = None
    MK2kPw: Optional[str] = None
    MKz1Tv: Optional[str] = None
    MQbqy9: Optional[str] = None
    MUzWB7: Optional[str] = None
    MjNTEu: Optional[str] = None
    N7Wq_c: Optional[str] = Field(None, alias="N7Wq/c")
    NAHlOT: Optional[str] = None
    NDmBum: Optional[str] = None
    NMHpYu: Optional[str] = None
    NYfs4P: Optional[str] = None
    NoResults: Optional[str] = None
    NqFp7f: Optional[str] = None
    O5tWsA: Optional[str] = None
    OIc_xw: Optional[str] = Field(None, alias="OIc/xw")
    OhkbDU: Optional[str] = None
    OjT4Gq: Optional[str] = None
    OthFOe: Optional[str] = None
    P5VGig: Optional[str] = None
    PGzyr2: Optional[str] = None
    PHVDJ8: Optional[str] = None
    PJLOZK: Optional[str] = None
    PZh7w_: Optional[str] = Field(None, alias="PZh7w+")
    PyzdXL: Optional[str] = None
    Q11y5F: Optional[str] = None
    Q23n_U: Optional[str] = Field(None, alias="Q23n/U")
    QEpb4w: Optional[str] = None
    QQFsPa: Optional[str] = None
    QXG_La: Optional[str] = Field(None, alias="QXG+La")
    QtvgOo: Optional[str] = None
    RJo0Z3: Optional[str] = None
    RRQ7fk: Optional[str] = None
    SKtwiU: Optional[str] = None
    SZjU9E: Optional[str] = None
    T6CwRX: Optional[str] = None
    TTeL00: Optional[str] = None
    TVtUVN: Optional[str] = None
    TkvM0N: Optional[str] = None
    UIZTzu: Optional[str] = None
    UQHsPm: Optional[str] = None
    UueyB1: Optional[str] = None
    VGYe8e: Optional[str] = None
    VMm7cd: Optional[str] = None
    VRmDFV: Optional[str] = None
    VWAeFy: Optional[str] = None
    VYWEFA: Optional[str] = None
    Vur4Pc: Optional[str] = None
    VzQxqn: Optional[str] = None
    WELugi: Optional[str] = None
    WLYW6_: Optional[str] = Field(None, alias="WLYW6/")
    WS6aEh: Optional[str] = None
    WU4UUT: Optional[str] = None
    WyUwHm: Optional[str] = None
    Wyr8z1: Optional[str] = None
    XBetJ4: Optional[str] = None
    XBrZ16: Optional[str] = None
    XEAUVf: Optional[str] = None
    XM2eiF: Optional[str] = None
    XR8z3v: Optional[str] = None
    XRFmnD: Optional[str] = None
    Y42Bah: Optional[str] = None
    YE1l8T: Optional[str] = None
    YaQUSr: Optional[str] = None
    Yn6mMH: Optional[str] = None
    Yr__el: Optional[str] = Field(None, alias="Yr+/el")
    ZOWwOS: Optional[str] = None
    ZPneo2: Optional[str] = None
    ZkjVLX: Optional[str] = None
    ZvV7k0: Optional[str] = None
    ZwXv1C: Optional[str] = None
    ZwfOoA: Optional[str] = None
    aNjcfm: Optional[str] = None
    aZxVvE: Optional[str] = None
    aoCYHZ: Optional[str] = None
    b7zond: Optional[str] = None
    cB8Agh: Optional[str] = None
    cCiGhf: Optional[str] = None
    cOtCHW: Optional[str] = None
    cPyO3E: Optional[str] = None
    cT5GPH: Optional[str] = None
    cbMqh0: Optional[str] = None
    d8Z26u: Optional[str] = None
    dQZuWX: Optional[str] = None
    dtDgwz: Optional[str] = None
    eAWOo4: Optional[str] = None
    eMHa_3: Optional[str] = Field(None, alias="eMHa+3")
    eZzIn6: Optional[str] = None
    ec_8jt: Optional[str] = Field(None, alias="ec+8jt")
    efG8Mm: Optional[str] = None
    elJBhI: Optional[str] = None
    f51mrK: Optional[str] = None
    fApUje: Optional[str] = None
    fGxzwb: Optional[str] = None
    fV65BM: Optional[str] = None
    fg3e0r: Optional[str] = None
    g12swr: Optional[str] = None
    g6e3dg: Optional[str] = None
    gEWjsM: Optional[str] = None
    gI1AIL: Optional[str] = None
    gaBIUj: Optional[str] = None
    h3dgEP: Optional[str] = None
    hT_s2i: Optional[str] = Field(None, alias="hT/s2i")
    hz2KSv: Optional[str] = None
    i5dhvD: Optional[str] = None
    iGb1sS: Optional[str] = None
    iVENNr: Optional[str] = None
    iYEhZN: Optional[str] = None
    ikBdCN: Optional[str] = None
    inFU_b: Optional[str] = Field(None, alias="inFU+b")
    jqpH_5: Optional[str] = Field(None, alias="jqpH+5")
    k_pu__: Optional[str] = Field(None, alias="k/pu+/")
    k8wgb4: Optional[str] = None
    ke3zkV: Optional[str] = None
    kkyKXY: Optional[str] = None
    krCZKf: Optional[str] = None
    l8bRxV: Optional[str] = None
    lAqxac: Optional[str] = None
    lNpHJU: Optional[str] = None
    lSPuI7: Optional[str] = None
    lbui_i: Optional[str] = Field(None, alias="lbui+i")
    mNZnPy: Optional[str] = None
    mNdVd9: Optional[str] = None
    mdq_wu: Optional[str] = Field(None, alias="mdq/wu")
    mhcNvv: Optional[str] = None
    nih7gu: Optional[str] = None
    nuU4t_: Optional[str] = Field(None, alias="nuU4t/")
    nxY39E: Optional[str] = None
    nzwRIp: Optional[str] = None
    o_2sFT: Optional[str] = Field(None, alias="o+2sFT")
    o5InVy: Optional[str] = None
    oM_Jlx: Optional[str] = Field(None, alias="oM/Jlx")
    oPQk4V: Optional[str] = None
    oQCGsZ: Optional[str] = None
    p55qbX: Optional[str] = None
    pFuHho: Optional[str] = None
    pagelinkheader: Optional[str] = None
    qAiQn0: Optional[str] = None
    qXzX3N: Optional[str] = None
    rNVPnk: Optional[str] = None
    rbZX5h: Optional[str] = None
    rhaGlx: Optional[str] = None
    rkGcmk: Optional[str] = None
    rzohCf: Optional[str] = None
    s8wxd4: Optional[str] = None
    sRM8i5: Optional[str] = None
    sX2X1Y: Optional[str] = None
    sXmy5o: Optional[str] = None
    sroDBL: Optional[str] = None
    subscriberCount: Optional[str] = None
    sxNj0_: Optional[str] = Field(None, alias="sxNj0/")
    t50FYQ: Optional[str] = None
    tGuLQJ: Optional[str] = None
    tHXDZ5: Optional[str] = None
    tcWR8m: Optional[str] = None
    tgKpK7: Optional[str] = None
    tm3FzH: Optional[str] = None
    tnrxhT: Optional[str] = None
    tvE5JV: Optional[str] = None
    u5SBAU: Optional[str] = None
    uKVTE3: Optional[str] = None
    uLjfHx: Optional[str] = None
    uWSAC7: Optional[str] = None
    uWzT_K: Optional[str] = Field(None, alias="uWzT/K")
    uXZM4v: Optional[str] = None
    ub_Qvb: Optional[str] = Field(None, alias="ub/Qvb")
    ud7shj: Optional[str] = None
    udmFsG: Optional[str] = None
    vQOevT: Optional[str] = None
    vTd_a8: Optional[str] = Field(None, alias="vTd+a8")
    vZuQb7: Optional[str] = None
    vg7g_j: Optional[str] = Field(None, alias="vg7g/j")
    vwXIZQ: Optional[str] = None
    vzHYL7: Optional[str] = None
    wHkOq4: Optional[str] = None
    xqD0n2: Optional[str] = None
    xrCy9R: Optional[str] = None
    xrLxhm: Optional[str] = None
    y19xMJ: Optional[str] = None
    yEAS_A: Optional[str] = Field(None, alias="yEAS+A")
    yil_vB: Optional[str] = Field(None, alias="yil/vB")
    zB_1uJ: Optional[str] = Field(None, alias="zB+1uJ")
    zJ_Qdi: Optional[str] = Field(None, alias="zJ+Qdi")
    zSzTfC: Optional[str] = None
    field_8U65x8: Optional[str] = Field(None, alias="8U65x8")
    field_8y4OLC: Optional[str] = Field(None, alias="8y4OLC")
    A9tP6F: Optional[str] = None
    UCXOkQ: Optional[str] = None
    ZNiFih: Optional[str] = None
    faBe0K: Optional[str] = None
    sS8dgY: Optional[str] = None
    zFaVQO: Optional[str] = None
    zMWPhb: Optional[str] = None


class PageProps(BaseModel):
    viewerInfo: Optional[ViewerInfo] = None
    localization: Optional[Localization] = None
    pageLinks: Optional[PageLinks] = None
    pageMetadata: Optional[PageMetadata] = None
    userProfile: UserProfile
    story: Story
    linkPreview: Optional[LinkPreview] = None
    lenses: Optional[List] = None
    curatedHighlights: Optional[List] = None
    spotlightHighlights: Optional[List[SpotlightHighlight]] = None
    showSnapExpiredToast: Optional[bool] = None
    lensCursor: Optional[str] = None
    curatedHighlightsCursor: Optional[str] = None
    spotlightHighlightsCursor: Optional[str] = None
    spotlightStoryMetadata: Optional[List[SpotlightStoryMetadatum]] = None
    gaid: Optional[Gaid] = None
    messages: Optional[Messages] = None

    @classmethod
    async def from_username(cls, username: str):
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)
            context = await browser.new_context(
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
            )
            page = await context.new_page()
            await page.goto(
                f"https://www.snapchat.com/add/{username}",
                wait_until="domcontentloaded",
            )
            content = await page.content()
            soup = BeautifulSoup(content, "html.parser")
            script = soup.find("script", attrs={"id": "__NEXT_DATA__"})
            data = json.loads(script.text)
            data = data["props"]["pageProps"]
        return cls(**data)
