# generated by datamodel-codegen:
#   filename:  stories.json
#   timestamp: 2024-10-05T18:49:20+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class MusicAssetInfo(BaseModel):
    should_mute_audio: Optional[bool] = None
    should_mute_audio_reason: Optional[str] = None
    title: Optional[str] = None
    display_artist: Optional[str] = None


class StoryMusicSticker(BaseModel):
    music_asset_info: Optional[MusicAssetInfo] = None
    id: None = None


class User(BaseModel):
    pk: Optional[str] = None
    id: None = None
    interop_messaging_user_fbid: None = None


class Caption(BaseModel):
    text: Optional[str] = None
    background_color: None = None
    background_color_alpha: None = None
    text_color: None = None
    text_size: None = None


class Candidate(BaseModel):
    height: Optional[int] = None
    url: Optional[str] = None
    width: Optional[int] = None


class ImageVersions2(BaseModel):
    candidates: Optional[List[Candidate]] = None


class VideoVersion(BaseModel):
    type: Optional[int] = None
    url: Optional[str] = None


class IgMention(BaseModel):
    full_name: Optional[str] = None
    username: Optional[str] = None


class StickerData(BaseModel):
    ig_mention: Optional[IgMention] = None


class BloksSticker(BaseModel):
    sticker_data: Optional[StickerData] = None
    id: Optional[str] = None


class StoryBloksSticker(BaseModel):
    x: Optional[float] = None
    y: Optional[float] = None
    width: Optional[float] = None
    height: Optional[float] = None
    rotation: Optional[int] = None
    bloks_sticker: Optional[BloksSticker] = None
    id: None = None


class StoryLink(BaseModel):
    url: Optional[str] = None


class StoryLinkSticker(BaseModel):
    x: Optional[float] = None
    y: Optional[float] = None
    width: Optional[float] = None
    height: Optional[float] = None
    rotation: Optional[int] = None
    story_link: Optional[StoryLink] = None
    id: None = None


class StoryFeedMediaItem(BaseModel):
    x: Optional[float] = None
    y: Optional[float] = None
    width: Optional[float] = None
    height: Optional[float] = None
    rotation: Optional[int] = None
    media_code: Optional[str] = None
    id: None = None
    product_type: Optional[str] = None


class ResharedStoryMediaAuthor(BaseModel):
    profile_pic_url: Optional[str] = None
    username: Optional[str] = None
    id: Optional[str] = None


class SharingFrictionInfo(BaseModel):
    should_have_sharing_friction: Optional[bool] = None
    bloks_app_url: None = None


class Item(BaseModel):
    pk: Optional[str] = None
    has_audio: Optional[bool] = None
    story_music_stickers: Optional[List[StoryMusicSticker]] = None
    user: Optional[User] = None
    inventory_source: None = None
    carousel_media_count: None = None
    carousel_media: None = None
    media_overlay_info: None = None
    caption: Optional[Caption] = None
    accessibility_caption: Optional[str] = None
    image_versions2: Optional[ImageVersions2] = None
    organic_tracking_token: Optional[str] = None
    original_width: Optional[int] = None
    original_height: Optional[int] = None
    taken_at: Optional[int] = None
    is_dash_eligible: Optional[int] = None
    number_of_qualities: Optional[int] = None
    video_dash_manifest: Optional[str] = None
    video_versions: Optional[List[VideoVersion]] = None
    media_type: Optional[int] = None
    visual_comment_reply_sticker_info: None = None
    story_bloks_stickers: Optional[List[StoryBloksSticker]] = None
    story_link_stickers: Optional[List[StoryLinkSticker]] = None
    story_hashtags: None = None
    story_locations: None = None
    story_feed_media: Optional[List[StoryFeedMediaItem]] = None
    text_post_share_to_ig_story_stickers: None = None
    story_countdowns: None = None
    story_questions: None = None
    story_sliders: None = None
    story_cta: None = None
    link: None = None
    reel_media_background: None = None
    link_text: None = None
    story_ad_cta_sticker: None = None
    video_duration: Optional[float] = None
    preview: None = None
    expiring_at: Optional[int] = None
    id: Optional[str] = None
    is_paid_partnership: Optional[bool] = None
    sponsor_tags: None = None
    reshared_story_media_author: Optional[ResharedStoryMediaAuthor] = None
    story_app_attribution: None = None
    has_translation: Optional[bool] = None
    boosted_status: None = None
    can_see_insights_as_brand: Optional[bool] = None
    boost_unavailable_identifier: None = None
    boost_unavailable_reason: None = None
    product_type: Optional[str] = None
    audience: None = None
    has_liked: Optional[bool] = None
    viewer_count: None = None
    viewers: None = None
    sharing_friction_info: Optional[SharingFrictionInfo] = None
    can_viewer_reshare: None = None
    ig_media_sharing_disabled: Optional[bool] = None
    can_reply: Optional[bool] = None
    can_reshare: Optional[bool] = None
    field__typename: Optional[str] = Field(None, alias="__typename")


class FriendshipStatus(BaseModel):
    following: Optional[bool] = None


class User1(BaseModel):
    username: Optional[str] = None
    id: Optional[str] = None
    pk: Optional[str] = None
    field__typename: Optional[str] = Field(None, alias="__typename")
    friendship_status: Optional[FriendshipStatus] = None
    interop_messaging_user_fbid: Optional[str] = None
    user_id: None = None
    profile_pic_url: Optional[str] = None
    is_verified: Optional[bool] = None
    transparency_label: None = None
    transparency_product: None = None
    transparency_product_enabled: Optional[bool] = None
    is_private: Optional[bool] = None


class ReelsMediaItem(BaseModel):
    id: Optional[str] = None
    items: Optional[List[Item]] = None
    user: Optional[User1] = None
    seen: Optional[int] = None
    reel_type: Optional[str] = None
    cover_media: None = None
    title: None = None
    latest_reel_media: Optional[int] = None
    muted: None = None


class Story(BaseModel):
    reels_media: Optional[List[ReelsMediaItem]] = None
