# generated by datamodel-codegen:
#   filename:  reel.json
#   timestamp: 2024-10-05T18:49:06+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Dimensions(BaseModel):
    height: Optional[int] = None
    width: Optional[int] = None


class SharingFrictionInfo(BaseModel):
    should_have_sharing_friction: Optional[bool] = None
    bloks_app_url: None = None


class DisplayResource(BaseModel):
    src: Optional[str] = None
    config_width: Optional[int] = None
    config_height: Optional[int] = None


class DashInfo(BaseModel):
    is_dash_eligible: Optional[bool] = None
    video_dash_manifest: None = None
    number_of_qualities: Optional[int] = None


class EdgeMediaToTaggedUser(BaseModel):
    edges: Optional[List] = None


class Node(BaseModel):
    created_at: Optional[str] = None
    text: Optional[str] = None


class Edge(BaseModel):
    node: Optional[Node] = None


class EdgeMediaToCaption(BaseModel):
    edges: Optional[List[Edge]] = None


class PageInfo(BaseModel):
    has_next_page: Optional[bool] = None
    end_cursor: Optional[str] = None


class Owner(BaseModel):
    id: Optional[str] = None
    is_verified: Optional[bool] = None
    profile_pic_url: Optional[str] = None
    username: Optional[str] = None


class EdgeLikedBy(BaseModel):
    count: Optional[int] = None


class PageInfo1(BaseModel):
    has_next_page: Optional[bool] = None
    end_cursor: None = None


class EdgeThreadedComments(BaseModel):
    count: Optional[int] = None
    page_info: Optional[PageInfo1] = None
    edges: Optional[List] = None


class Node1(BaseModel):
    id: Optional[str] = None
    text: Optional[str] = None
    created_at: Optional[int] = None
    did_report_as_spam: Optional[bool] = None
    owner: Optional[Owner] = None
    viewer_has_liked: Optional[bool] = None
    edge_liked_by: Optional[EdgeLikedBy] = None
    is_restricted_pending: Optional[bool] = None
    edge_threaded_comments: Optional[EdgeThreadedComments] = None


class Edge1(BaseModel):
    node: Optional[Node1] = None


class EdgeMediaToParentComment(BaseModel):
    count: Optional[int] = None
    page_info: Optional[PageInfo] = None
    edges: Optional[List[Edge1]] = None


class EdgeMediaToHoistedComment(BaseModel):
    edges: Optional[List] = None


class Node2(BaseModel):
    id: Optional[str] = None
    text: Optional[str] = None
    created_at: Optional[int] = None
    did_report_as_spam: Optional[bool] = None
    owner: Optional[Owner] = None
    viewer_has_liked: Optional[bool] = None
    edge_liked_by: Optional[EdgeLikedBy] = None
    is_restricted_pending: Optional[bool] = None


class Edge2(BaseModel):
    node: Optional[Node2] = None


class EdgeMediaPreviewComment(BaseModel):
    count: Optional[int] = None
    edges: Optional[List[Edge2]] = None


class EdgeMediaPreviewLike(BaseModel):
    count: Optional[int] = None
    edges: Optional[List] = None


class EdgeMediaToSponsorUser(BaseModel):
    edges: Optional[List] = None


class EdgeOwnerToTimelineMedia(BaseModel):
    count: Optional[int] = None


class EdgeFollowedBy(BaseModel):
    count: Optional[int] = None


class Owner2(BaseModel):
    id: Optional[str] = None
    is_verified: Optional[bool] = None
    profile_pic_url: Optional[str] = None
    username: Optional[str] = None
    blocked_by_viewer: Optional[bool] = None
    restricted_by_viewer: None = None
    followed_by_viewer: Optional[bool] = None
    full_name: Optional[str] = None
    has_blocked_viewer: Optional[bool] = None
    is_embeds_disabled: Optional[bool] = None
    is_private: Optional[bool] = None
    is_unpublished: Optional[bool] = None
    requested_by_viewer: Optional[bool] = None
    pass_tiering_recommendation: Optional[bool] = None
    edge_owner_to_timeline_media: Optional[EdgeOwnerToTimelineMedia] = None
    edge_followed_by: Optional[EdgeFollowedBy] = None


class EdgeWebMediaToRelatedMedia(BaseModel):
    edges: Optional[List] = None


class ClipsMusicAttributionInfo(BaseModel):
    artist_name: Optional[str] = None
    song_name: Optional[str] = None
    uses_original_audio: Optional[bool] = None
    should_mute_audio: Optional[bool] = None
    should_mute_audio_reason: Optional[str] = None
    audio_id: Optional[str] = None


class EdgeMediaPreviewLike1(BaseModel):
    count: Optional[int] = None


class EdgeMediaPreviewComment1(BaseModel):
    count: Optional[int] = None


class Owner3(BaseModel):
    id: Optional[str] = None
    username: Optional[str] = None


class Node4(BaseModel):
    field__typename: Optional[str] = Field(None, alias="__typename")
    id: Optional[str] = None
    shortcode: Optional[str] = None
    edge_media_preview_like: Optional[EdgeMediaPreviewLike1] = None
    edge_media_preview_comment: Optional[EdgeMediaPreviewComment1] = None
    thumbnail_src: Optional[str] = None
    owner: Optional[Owner3] = None
    gating_info: None = None
    sharing_friction_info: Optional[SharingFrictionInfo] = None
    media_overlay_info: None = None
    is_video: Optional[bool] = None
    accessibility_caption: Optional[str] = None


class Edge4(BaseModel):
    node: Optional[Node4] = None


class EdgeOwnerToTimelineMedia1(BaseModel):
    count: Optional[int] = None
    edges: Optional[List[Edge4]] = None


class Node3(BaseModel):
    id: Optional[str] = None
    full_name: Optional[str] = None
    is_private: Optional[bool] = None
    is_verified: Optional[bool] = None
    profile_pic_url: Optional[str] = None
    username: Optional[str] = None
    edge_followed_by: Optional[EdgeFollowedBy] = None
    edge_owner_to_timeline_media: Optional[EdgeOwnerToTimelineMedia1] = None


class Edge3(BaseModel):
    node: Optional[Node3] = None


class EdgeRelatedProfiles(BaseModel):
    edges: Optional[List[Edge3]] = None


class ShortcodeMedia(BaseModel):
    field__typename: Optional[str] = Field(None, alias="__typename")
    id: Optional[str] = None
    shortcode: Optional[str] = None
    dimensions: Optional[Dimensions] = None
    gating_info: None = None
    fact_check_overall_rating: None = None
    fact_check_information: None = None
    sensitivity_friction_info: None = None
    sharing_friction_info: Optional[SharingFrictionInfo] = None
    media_overlay_info: None = None
    media_preview: Optional[str] = None
    display_url: Optional[str] = None
    display_resources: Optional[List[DisplayResource]] = None
    accessibility_caption: None = None
    dash_info: Optional[DashInfo] = None
    has_audio: Optional[bool] = None
    video_url: Optional[str] = None
    video_view_count: Optional[int] = None
    video_play_count: Optional[int] = None
    is_video: Optional[bool] = None
    tracking_token: Optional[str] = None
    upcoming_event: None = None
    edge_media_to_tagged_user: Optional[EdgeMediaToTaggedUser] = None
    edge_media_to_caption: Optional[EdgeMediaToCaption] = None
    can_see_insights_as_brand: Optional[bool] = None
    caption_is_edited: Optional[bool] = None
    has_ranked_comments: Optional[bool] = None
    like_and_view_counts_disabled: Optional[bool] = None
    edge_media_to_parent_comment: Optional[EdgeMediaToParentComment] = None
    edge_media_to_hoisted_comment: Optional[EdgeMediaToHoistedComment] = None
    edge_media_preview_comment: Optional[EdgeMediaPreviewComment] = None
    comments_disabled: Optional[bool] = None
    commenting_disabled_for_viewer: Optional[bool] = None
    taken_at_timestamp: Optional[int] = None
    edge_media_preview_like: Optional[EdgeMediaPreviewLike] = None
    edge_media_to_sponsor_user: Optional[EdgeMediaToSponsorUser] = None
    is_affiliate: Optional[bool] = None
    is_paid_partnership: Optional[bool] = None
    location: None = None
    nft_asset_info: None = None
    viewer_has_liked: Optional[bool] = None
    viewer_has_saved: Optional[bool] = None
    viewer_has_saved_to_collection: Optional[bool] = None
    viewer_in_photo_of_you: Optional[bool] = None
    viewer_can_reshare: Optional[bool] = None
    owner: Optional[Owner2] = None
    is_ad: Optional[bool] = None
    edge_web_media_to_related_media: Optional[EdgeWebMediaToRelatedMedia] = None
    coauthor_producers: Optional[List] = None
    pinned_for_users: Optional[List] = None
    encoding_status: None = None
    is_published: Optional[bool] = None
    product_type: Optional[str] = None
    title: Optional[str] = None
    video_duration: Optional[float] = None
    thumbnail_src: Optional[str] = None
    clips_music_attribution_info: Optional[ClipsMusicAttributionInfo] = None
    edge_related_profiles: Optional[EdgeRelatedProfiles] = None


class Graphql(BaseModel):
    shortcode_media: Optional[ShortcodeMedia] = None


class Reel(BaseModel):
    graphql: Optional[Graphql] = None
    showQRModal: Optional[bool] = None
