# generated by datamodel-codegen:
#   filename:  kick.json
#   timestamp: 2024-10-16T19:20:42+00:00

from __future__ import annotations

from typing import Any, List, Optional, Union

from pydantic import BaseModel


class BadgeImage(BaseModel):
    srcset: Optional[str] = None
    src: Optional[str] = None


class SubscriberBadge(BaseModel):
    id: Optional[int] = None
    channel_id: Optional[int] = None
    months: Optional[int] = None
    badge_image: Optional[BadgeImage] = None


class BannerImage(BaseModel):
    responsive: Optional[str] = None
    url: Optional[str] = None


class Banner(BaseModel):
    responsive: Optional[str] = None
    url: Optional[str] = None


class Category(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    slug: Optional[str] = None
    icon: Optional[str] = None


class RecentCategory(BaseModel):
    id: Optional[int] = None
    category_id: Optional[int] = None
    name: Optional[str] = None
    slug: Optional[str] = None
    tags: Optional[List[str]] = None
    description: Optional[Any] = None
    deleted_at: Optional[Any] = None
    viewers: Optional[int] = None
    banner: Optional[Banner] = None
    category: Optional[Category] = None


class Thumbnail(BaseModel):
    responsive: Optional[str] = None
    url: Optional[str] = None


class Category1(BaseModel):
    id: Optional[int] = None
    category_id: Optional[int] = None
    name: Optional[str] = None
    slug: Optional[str] = None
    tags: Optional[List[str]] = None
    description: Optional[Any] = None
    deleted_at: Optional[Any] = None
    viewers: Optional[int] = None
    category: Optional[Category] = None


class Livestream(BaseModel):
    id: Optional[int] = None
    slug: Optional[str] = None
    channel_id: Optional[int] = None
    created_at: Optional[str] = None
    session_title: Optional[str] = None
    is_live: Optional[bool] = None
    risk_level_id: Optional[Any] = None
    start_time: Optional[str] = None
    source: Optional[Any] = None
    twitch_channel: Optional[Any] = None
    duration: Optional[int] = None
    language: Optional[str] = None
    is_mature: Optional[bool] = None
    viewer_count: Optional[int] = 0
    thumbnail: Optional[Thumbnail] = None
    viewers: Optional[int] = None
    categories: Optional[List[Category1]] = None
    tags: Optional[List] = None


class OfflineBannerImage(BaseModel):
    src: Optional[str] = None
    srcset: Optional[str] = None


class User(BaseModel):
    id: Optional[int] = None
    username: Optional[str] = None
    agreed_to_terms: Optional[bool] = None
    email_verified_at: Optional[str] = None
    bio: Optional[str] = None
    country: Optional[str] = None
    state: Optional[str] = None
    city: Optional[str] = None
    instagram: Optional[str] = None
    twitter: Optional[str] = None
    youtube: Optional[str] = None
    discord: Optional[str] = None
    tiktok: Optional[str] = None
    facebook: Optional[str] = None
    profile_pic: Optional[str] = None


class Chatroom(BaseModel):
    id: Optional[int] = None
    chatable_type: Optional[str] = None
    channel_id: Optional[int] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    chat_mode_old: Optional[str] = None
    chat_mode: Optional[str] = None
    slow_mode: Optional[bool] = None
    chatable_id: Optional[int] = None
    followers_mode: Optional[bool] = None
    subscribers_mode: Optional[bool] = None
    emotes_mode: Optional[bool] = None
    message_interval: Optional[int] = None
    following_min_duration: Optional[int] = None


class AscendingLink(BaseModel):
    id: Optional[int] = None
    channel_id: Optional[int] = None
    description: Optional[str] = None
    link: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    order: Optional[int] = None
    title: Optional[str] = None


class Plan(BaseModel):
    id: Optional[int] = None
    channel_id: Optional[int] = None
    stripe_plan_id: Optional[str] = None
    amount: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class Thumbnail1(BaseModel):
    src: Optional[str] = None
    srcset: Optional[str] = None


class Category4(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    slug: Optional[str] = None
    icon: Optional[str] = None


class Category3(BaseModel):
    id: Optional[int] = None
    category_id: Optional[int] = None
    name: Optional[str] = None
    slug: Optional[str] = None
    tags: Optional[List[str]] = None
    description: Optional[Any] = None
    deleted_at: Optional[Any] = None
    viewers: Optional[int] = None
    banner: Optional[Banner] = None
    category: Optional[Category4] = None


class Video(BaseModel):
    id: Optional[int] = None
    live_stream_id: Optional[int] = None
    slug: Optional[Any] = None
    thumb: Optional[Any] = None
    s3: Optional[Any] = None
    trading_platform_id: Optional[Any] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    uuid: Optional[str] = None
    views: Optional[int] = None
    deleted_at: Optional[Any] = None


class PreviousLivestream(BaseModel):
    id: Optional[int] = None
    slug: Optional[str] = None
    channel_id: Optional[int] = None
    created_at: Optional[str] = None
    session_title: Optional[str] = None
    is_live: Optional[bool] = None
    risk_level_id: Optional[Any] = None
    start_time: Optional[str] = None
    source: Optional[Any] = None
    twitch_channel: Optional[Any] = None
    duration: Optional[int] = None
    language: Optional[str] = None
    is_mature: Optional[bool] = None
    viewer_count: Optional[int] = None
    thumbnail: Optional[Thumbnail1] = None
    views: Optional[int] = None
    tags: Optional[List] = None
    categories: Optional[List[Category3]] = None
    video: Optional[Video] = None


class Verified(BaseModel):
    id: Optional[int] = None
    channel_id: Optional[int] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class GeneratedConversions(BaseModel):
    fullsize: Optional[bool] = None
    medium: Optional[bool] = None


class CustomProperties(BaseModel):
    generated_conversions: Optional[GeneratedConversions] = None


class Fullsize(BaseModel):
    urls: Optional[List[str]] = None
    base64svg: Optional[str] = None


class ResponsiveImages(BaseModel):
    fullsize: Optional[Fullsize] = None


class MediaItem(BaseModel):
    id: Optional[int] = None
    model_type: Optional[str] = None
    model_id: Optional[int] = None
    collection_name: Optional[str] = None
    name: Optional[str] = None
    file_name: Optional[str] = None
    mime_type: Optional[str] = None
    disk: Optional[str] = None
    size: Optional[int] = None
    manipulations: Optional[list] = None
    custom_properties: Optional[CustomProperties] = None
    responsive_images: Optional[Union[List, ResponsiveImages]] = None
    order_column: Optional[int] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    uuid: Optional[str] = None
    conversions_disk: Optional[str] = None

    class Config:
        protected_namespaces = ()


class KickChannel(BaseModel):
    id: Optional[int] = None
    user_id: Optional[int] = None
    slug: Optional[str] = None
    is_banned: Optional[bool] = None
    playback_url: Optional[str] = None
    name_updated_at: Optional[Any] = None
    vod_enabled: Optional[bool] = None
    subscription_enabled: Optional[bool] = None
    followersCount: Optional[int] = 0
    subscriber_badges: Optional[List[SubscriberBadge]] = None
    banner_image: Optional[BannerImage] = None
    recent_categories: Optional[List[RecentCategory]] = None
    livestream: Optional[Livestream] = None
    role: Optional[Any] = None
    muted: Optional[bool] = None
    follower_badges: Optional[List] = None
    offline_banner_image: Optional[OfflineBannerImage] = None
    can_host: Optional[bool] = None
    user: Optional[User] = None
    chatroom: Optional[Chatroom] = None
    ascending_links: Optional[List[AscendingLink]] = None
    plan: Optional[Plan] = None
    previous_livestreams: Optional[List[PreviousLivestream]] = None
    verified: Optional[Verified] = None
    media: Optional[List[MediaItem]] = None
