pip install -U git+https://github.com/Gorialis/jishaku
pip install -U git+https://github.com/Rapptz/discord.py
pip install -U cashews
pip install -U aiohttp
pip install -U asyncpg
pip install -U cairosvg
pip install -U anyio
pip install -U colorthief
pip install -U tornado
pip install -U playwright
pip install -U pydantic
pip install -U aiomisc
pip install -U bs4
pip install -U xxhash
pip install -U lru-dict
pip install -U redis
pip install -U rich
pip install -U boltons
pip install -U asyncspotify
pip install -U rapidfuzz
pip install -U dateparser
pip install -U pomice
pip install -U arrow
pip install -U roblox
pip install -U shazamio
pip install -U stackprinter
pip install -U validators
pip install -U psutil
pip install -U asyncpraw
pip install -U humanfriendly
pip install -U humanize
pip install -U yt-dlp
