# generated by datamodel-codegen:
#   filename:  post.json
#   timestamp: 2024-10-06T19:04:29+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel, Field


class User(BaseModel):
    pk: Optional[int] = None
    pk_id: Optional[str] = None
    id: Optional[str] = None
    full_name: Optional[str] = None
    is_private: Optional[bool] = None
    is_unpublished: Optional[bool] = None
    strong_id__: Optional[str] = None
    fbid_v2: Optional[int] = None
    username: Optional[str] = None
    is_verified: Optional[bool] = None
    profile_pic_url: Optional[str] = None


class Caption(BaseModel):
    bit_flags: Optional[int] = None
    created_at: Optional[int] = None
    created_at_utc: Optional[int] = None
    did_report_as_spam: Optional[bool] = None
    is_ranked_comment: Optional[bool] = None
    pk: Optional[str] = None
    share_enabled: Optional[bool] = None
    content_type: Optional[str] = None
    media_id: Optional[int] = None
    status: Optional[str] = None
    type: Optional[int] = None
    user_id: Optional[int] = None
    strong_id__: Optional[str] = None
    text: Optional[str] = None
    user: Optional[User] = None
    is_covered: Optional[bool] = None
    private_reply_status: Optional[int] = None


class SharingFrictionInfo(BaseModel):
    bloks_app_url: Optional[Any] = None
    should_have_sharing_friction: Optional[bool] = None
    sharing_friction_payload: Optional[Any] = None


class FbUserTags(BaseModel):
    in_: Optional[List] = None


class FanClubInfo(BaseModel):
    autosave_to_exclusive_highlight: Optional[Any] = None
    connected_member_count: Optional[Any] = None
    fan_club_id: Optional[Any] = None
    fan_club_name: Optional[Any] = None
    has_enough_subscribers_for_ssc: Optional[Any] = None
    is_fan_club_gifting_eligible: Optional[Any] = None
    is_fan_club_referral_eligible: Optional[Any] = None
    is_free_trial_eligible: Optional[Any] = None
    largest_public_bc_id: Optional[Any] = None
    subscriber_count: Optional[Any] = None
    fan_consideration_page_revamp_eligiblity: Optional[Any] = None


class FriendshipStatus(BaseModel):
    following: Optional[bool] = None
    is_bestie: Optional[bool] = None
    is_feed_favorite: Optional[bool] = None
    is_restricted: Optional[bool] = None


class HdProfilePicUrlInfo(BaseModel):
    height: Optional[int] = None
    url: Optional[str] = None
    width: Optional[int] = None


class User1(BaseModel):
    fbid_v2: Optional[int] = None
    feed_post_reshare_disabled: Optional[bool] = None
    full_name: Optional[str] = None
    id: Optional[str] = None
    is_private: Optional[bool] = None
    is_unpublished: Optional[bool] = None
    pk: Optional[int] = None
    pk_id: Optional[str] = None
    show_account_transparency_details: Optional[bool] = None
    strong_id__: Optional[str] = None
    third_party_downloads_enabled: Optional[int] = None
    account_type: Optional[int] = None
    account_badges: Optional[List] = None
    fan_club_info: Optional[FanClubInfo] = None
    friendship_status: Optional[FriendshipStatus] = None
    has_anonymous_profile_picture: Optional[bool] = None
    hd_profile_pic_url_info: Optional[HdProfilePicUrlInfo] = None
    is_favorite: Optional[bool] = None
    is_verified: Optional[bool] = None
    profile_pic_url: Optional[str] = None
    transparency_product_enabled: Optional[bool] = None
    username: Optional[str] = None
    latest_reel_media: Optional[int] = None
    can_see_quiet_post_attribution: Optional[bool] = None


class Owner(BaseModel):
    fbid_v2: Optional[int] = None
    feed_post_reshare_disabled: Optional[bool] = None
    full_name: Optional[str] = None
    id: Optional[str] = None
    is_private: Optional[bool] = None
    is_unpublished: Optional[bool] = None
    pk: Optional[int] = None
    pk_id: Optional[str] = None
    show_account_transparency_details: Optional[bool] = None
    strong_id__: Optional[str] = None
    third_party_downloads_enabled: Optional[int] = None
    account_type: Optional[int] = None
    account_badges: Optional[List] = None
    fan_club_info: Optional[FanClubInfo] = None
    friendship_status: Optional[FriendshipStatus] = None
    has_anonymous_profile_picture: Optional[bool] = None
    hd_profile_pic_url_info: Optional[HdProfilePicUrlInfo] = None
    is_favorite: Optional[bool] = None
    is_verified: Optional[bool] = None
    profile_pic_url: Optional[str] = None
    transparency_product_enabled: Optional[bool] = None
    username: Optional[str] = None
    latest_reel_media: Optional[int] = None
    can_see_quiet_post_attribution: Optional[bool] = None


class Candidate(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class ImageVersions2(BaseModel):
    candidates: Optional[List[Candidate]] = None
    additional_candidates: Optional[Any] = None
    scrubber_spritesheet_info_candidates: Optional[Any] = None


class MediaNotes(BaseModel):
    items: Optional[List] = None


class MusicAssetInfo(BaseModel):
    allows_saving: Optional[bool] = None
    artist_id: Optional[str] = None
    audio_asset_id: Optional[str] = None
    audio_cluster_id: Optional[str] = None
    cover_artwork_thumbnail_uri: Optional[str] = None
    cover_artwork_uri: Optional[str] = None
    dark_message: Optional[Any] = None
    dash_manifest: Optional[Any] = None
    display_artist: Optional[str] = None
    duration_in_ms: Optional[int] = None
    fast_start_progressive_download_url: Optional[str] = None
    has_lyrics: Optional[bool] = None
    highlight_start_times_in_ms: Optional[List[int]] = None
    id: Optional[str] = None
    ig_username: Optional[str] = None
    is_eligible_for_audio_effects: Optional[bool] = None
    is_explicit: Optional[bool] = None
    progressive_download_url: Optional[str] = None
    reactive_audio_download_url: Optional[Any] = None
    sanitized_title: Optional[Any] = None
    subtitle: Optional[str] = None
    title: Optional[str] = None
    web_30s_preview_download_url: Optional[str] = None
    is_eligible_for_vinyl_sticker: Optional[bool] = None
    lyrics: Optional[Any] = None


class IgArtist(BaseModel):
    pk: Optional[int] = None
    pk_id: Optional[str] = None
    id: Optional[str] = None
    full_name: Optional[str] = None
    is_private: Optional[bool] = None
    strong_id__: Optional[str] = None
    username: Optional[str] = None
    is_verified: Optional[bool] = None
    profile_pic_id: Optional[str] = None
    profile_pic_url: Optional[str] = None


class AudioMutingInfo(BaseModel):
    allow_audio_editing: Optional[bool] = None
    mute_audio: Optional[bool] = None
    mute_reason: Optional[Any] = None
    mute_reason_str: Optional[str] = None
    show_muted_audio_toast: Optional[bool] = None


class MusicConsumptionInfo(BaseModel):
    allow_media_creation_with_music: Optional[bool] = None
    audio_asset_start_time_in_ms: Optional[int] = None
    contains_lyrics: Optional[Any] = None
    derived_content_id: Optional[Any] = None
    display_labels: Optional[Any] = None
    formatted_clips_media_count: Optional[Any] = None
    ig_artist: Optional[IgArtist] = None
    is_bookmarked: Optional[bool] = None
    is_trending_in_clips: Optional[bool] = None
    overlap_duration_in_ms: Optional[int] = None
    placeholder_profile_pic_url: Optional[str] = None
    should_allow_music_editing: Optional[bool] = None
    should_mute_audio: Optional[bool] = None
    should_mute_audio_reason: Optional[str] = None
    should_mute_audio_reason_type: Optional[Any] = None
    should_render_soundwave: Optional[bool] = None
    trend_rank: Optional[Any] = None
    previous_trend_rank: Optional[Any] = None
    audio_filter_infos: Optional[List] = None
    audio_muting_info: Optional[AudioMutingInfo] = None


class MusicInfo(BaseModel):
    music_canonical_id: Optional[Any] = None
    music_asset_info: Optional[MusicAssetInfo] = None
    music_consumption_info: Optional[MusicConsumptionInfo] = None


class MusicMetadata(BaseModel):
    audio_type: Optional[str] = None
    music_canonical_id: Optional[str] = None
    pinned_media_ids: Optional[List] = None
    music_info: Optional[MusicInfo] = None
    original_sound_info: Optional[Any] = None


class GenAiDetectionMethod(BaseModel):
    detection_method: Optional[str] = None


class CommentInformTreatment(BaseModel):
    action_type: Optional[Any] = None
    should_have_inform_treatment: Optional[bool] = None
    text: Optional[str] = None
    url: Optional[Any] = None


class VideoVersion(BaseModel):
    height: Optional[int] = None
    id: Optional[str] = None
    type: Optional[int] = None
    url: Optional[str] = None
    width: Optional[int] = None


class AchievementsInfo(BaseModel):
    num_earned_achievements: Optional[Any] = None
    show_achievements: Optional[bool] = None


class AudioReattributionInfo(BaseModel):
    should_allow_restore: Optional[bool] = None


class AdditionalAudioInfo(BaseModel):
    additional_audio_username: Optional[Any] = None
    audio_reattribution_info: Optional[AudioReattributionInfo] = None


class AudioRankingInfo(BaseModel):
    best_audio_cluster_id: Optional[str] = None


class BrandedContentTagInfo(BaseModel):
    can_add_tag: Optional[bool] = None


class ContentAppreciationInfo(BaseModel):
    enabled: Optional[bool] = None
    entry_point_container: Optional[Any] = None


class MashupInfo(BaseModel):
    mashups_allowed: Optional[bool] = None
    is_reuse_allowed: Optional[bool] = None
    can_toggle_mashups_allowed: Optional[bool] = None
    has_been_mashed_up: Optional[bool] = None
    is_light_weight_check: Optional[bool] = None
    is_light_weight_reuse_allowed_check: Optional[bool] = None
    formatted_mashups_count: Optional[Any] = None
    original_media: Optional[Any] = None
    privacy_filtered_mashups_media_count: Optional[Any] = None
    non_privacy_filtered_mashups_media_count: Optional[int] = None
    mashup_type: Optional[Any] = None
    is_creator_requesting_mashup: Optional[bool] = None
    has_nonmimicable_additional_audio: Optional[bool] = None
    is_pivot_page_available: Optional[bool] = None


class IgArtist1(BaseModel):
    pk: Optional[int] = None
    pk_id: Optional[str] = None
    id: Optional[str] = None
    full_name: Optional[str] = None
    is_private: Optional[bool] = None
    strong_id__: Optional[str] = None
    username: Optional[str] = None
    is_verified: Optional[bool] = None
    profile_pic_url: Optional[str] = None


class ConsumptionInfo(BaseModel):
    display_media_id: Optional[Any] = None
    is_bookmarked: Optional[bool] = None
    is_trending_in_clips: Optional[bool] = None
    should_mute_audio_reason: Optional[str] = None
    should_mute_audio_reason_type: Optional[Any] = None


class OriginalSoundInfo(BaseModel):
    allow_creator_to_rename: Optional[bool] = None
    audio_asset_id: Optional[int] = None
    attributed_custom_audio_asset_id: Optional[Any] = None
    can_remix_be_shared_to_fb: Optional[bool] = None
    can_remix_be_shared_to_fb_expansion: Optional[bool] = None
    dash_manifest: Optional[str] = None
    duration_in_ms: Optional[int] = None
    formatted_clips_media_count: Optional[Any] = None
    hide_remixing: Optional[bool] = None
    ig_artist: Optional[IgArtist1] = None
    is_audio_automatically_attributed: Optional[bool] = None
    is_eligible_for_audio_effects: Optional[bool] = None
    is_eligible_for_vinyl_sticker: Optional[bool] = None
    is_explicit: Optional[bool] = None
    is_original_audio_download_eligible: Optional[bool] = None
    is_reuse_disabled: Optional[bool] = None
    is_xpost_from_fb: Optional[bool] = None
    music_canonical_id: Optional[Any] = None
    oa_owner_is_music_artist: Optional[bool] = None
    original_audio_subtype: Optional[str] = None
    original_audio_title: Optional[str] = None
    original_media_id: Optional[float] = None
    progressive_download_url: Optional[str] = None
    should_mute_audio: Optional[bool] = None
    time_created: Optional[int] = None
    trend_rank: Optional[Any] = None
    previous_trend_rank: Optional[Any] = None
    overlap_duration_in_ms: Optional[Any] = None
    audio_asset_start_time_in_ms: Optional[Any] = None
    audio_filter_infos: Optional[List] = None
    audio_parts: Optional[List] = None
    audio_parts_by_filter: Optional[List] = None
    consumption_info: Optional[ConsumptionInfo] = None
    xpost_fb_creator_info: Optional[Any] = None


class ClipsMetadata(BaseModel):
    breaking_content_info: Optional[Any] = None
    breaking_creator_info: Optional[Any] = None
    clips_creation_entry_point: Optional[str] = None
    featured_label: Optional[Any] = None
    is_public_chat_welcome_video: Optional[bool] = None
    is_shared_to_fb: Optional[bool] = None
    professional_clips_upsell_type: Optional[int] = None
    reels_on_the_rise_info: Optional[Any] = None
    show_tips: Optional[Any] = None
    achievements_info: Optional[AchievementsInfo] = None
    additional_audio_info: Optional[AdditionalAudioInfo] = None
    asset_recommendation_info: Optional[Any] = None
    audio_ranking_info: Optional[AudioRankingInfo] = None
    audio_type: Optional[str] = None
    branded_content_tag_info: Optional[BrandedContentTagInfo] = None
    challenge_info: Optional[Any] = None
    content_appreciation_info: Optional[ContentAppreciationInfo] = None
    contextual_highlight_info: Optional[Any] = None
    cutout_sticker_info: Optional[List] = None
    disable_use_in_clips_client_cache: Optional[bool] = None
    external_media_info: Optional[Any] = None
    is_fan_club_promo_video: Optional[bool] = None
    mashup_info: Optional[MashupInfo] = None
    merchandising_pill_info: Optional[Any] = None
    music_canonical_id: Optional[str] = None
    music_info: Optional[Any] = None
    nux_info: Optional[Any] = None
    original_sound_info: Optional[OriginalSoundInfo] = None
    originality_info: Optional[Any] = None
    reusable_text_attribute_string: Optional[Any] = None
    reusable_text_info: Optional[Any] = None
    shopping_info: Optional[Any] = None
    show_achievements: Optional[bool] = None
    template_info: Optional[Any] = None
    viewer_interaction_settings: Optional[Any] = None


class ImageVersions21(BaseModel):
    candidates: Optional[List[Candidate]] = None


class FbUserTags1(BaseModel):
    in_: Optional[List] = Field(None, alias="in")


class CarouselMediaItem(BaseModel):
    id: Optional[str] = None
    explore_pivot_grid: Optional[bool] = None
    carousel_parent_id: Optional[str] = None
    strong_id__: Optional[str] = None
    pk: Optional[int] = None
    commerciality_status: Optional[str] = None
    taken_at: Optional[int] = None
    product_type: Optional[str] = None
    media_type: Optional[int] = None
    image_versions2: Optional[ImageVersions21] = None
    original_width: Optional[int] = None
    original_height: Optional[int] = None
    preview: Optional[str] = None
    featured_products: Optional[List] = None
    fb_user_tags: Optional[FbUserTags1] = None
    shop_routing_user_id: Optional[Any] = None
    sharing_friction_info: Optional[SharingFrictionInfo] = None
    product_suggestions: Optional[List] = None
    video_sticker_locales: Optional[List] = None


class Item(BaseModel):
    taken_at: Optional[int] = None
    pk: Optional[int] = None
    id: Optional[str] = None
    fbid: Optional[int] = None
    device_timestamp: Optional[int] = None
    caption_is_edited: Optional[bool] = None
    strong_id__: Optional[str] = None
    deleted_reason: Optional[int] = None
    has_shared_to_fb: Optional[int] = None
    has_delayed_metadata: Optional[bool] = None
    is_quiet_post: Optional[bool] = None
    mezql_token: Optional[str] = None
    share_count_disabled: Optional[bool] = None
    is_visual_reply_commenter_notice_enabled: Optional[bool] = None
    like_and_view_counts_disabled: Optional[bool] = None
    is_post_live_clips_media: Optional[bool] = None
    client_cache_key: Optional[str] = None
    integrity_review_decision: Optional[str] = None
    should_request_ads: Optional[bool] = None
    is_reshare_of_text_post_app_media_in_ig: Optional[bool] = None
    has_privately_liked: Optional[bool] = None
    filter_type: Optional[int] = None
    can_see_insights_as_brand: Optional[bool] = None
    media_type: Optional[int] = None
    code: Optional[str] = None
    caption: Optional[Caption] = None
    sharing_friction_info: Optional[SharingFrictionInfo] = None
    timeline_pinned_user_ids: Optional[List] = None
    play_count: Optional[Any] = None
    has_views_fetching: Optional[bool] = None
    creator_viewer_insights: Optional[Any] = None
    fb_user_tags: Optional[FbUserTags] = None
    coauthor_producers: Optional[List] = None
    coauthor_producer_can_see_organic_insights: Optional[bool] = None
    invited_coauthor_producers: Optional[List] = None
    is_in_profile_grid: Optional[bool] = None
    profile_grid_control_enabled: Optional[bool] = None
    media_cropping_info: Optional[Any] = None
    user: Optional[User1] = None
    owner: Optional[Owner] = None
    image_versions2: Optional[ImageVersions2] = None
    original_width: Optional[int] = None
    original_height: Optional[int] = None
    is_artist_pick: Optional[Any] = None
    media_notes: Optional[MediaNotes] = None
    enable_media_notes_production: Optional[bool] = None
    product_type: Optional[str] = None
    is_paid_partnership: Optional[bool] = None
    music_metadata: Optional[MusicMetadata] = None
    organic_tracking_token: Optional[str] = None
    is_third_party_downloads_eligible: Optional[Any] = None
    ig_media_sharing_disabled: Optional[bool] = None
    are_remixes_crosspostable: Optional[Any] = None
    boost_unavailable_identifier: Optional[Any] = None
    boost_unavailable_reason: Optional[Any] = None
    boost_unavailable_reason_v2: Optional[Any] = None
    subscribe_cta_visible: Optional[bool] = None
    is_cutout_sticker_allowed: Optional[bool] = None
    gen_ai_detection_method: Optional[GenAiDetectionMethod] = None
    fb_aggregated_like_count: Optional[int] = None
    fb_aggregated_comment_count: Optional[int] = None
    has_high_risk_gen_ai_inform_treatment: Optional[bool] = None
    open_carousel_show_follow_button: Optional[bool] = None
    is_tagged_media_shared_to_viewer_profile_grid: Optional[bool] = None
    should_show_author_pog_for_tagged_media_shared_to_profile_grid: Optional[bool] = (
        None
    )
    is_eligible_for_media_note_recs_nux: Optional[bool] = None
    is_social_ufi_disabled: Optional[bool] = None
    meta_ai_suggested_prompts: Optional[List] = None
    can_reply: Optional[bool] = None
    can_view_more_preview_comments: Optional[bool] = None
    preview_comments: Optional[List] = None
    comment_count: Optional[int] = None
    hide_view_all_comment_entrypoint: Optional[bool] = None
    inline_composer_display_condition: Optional[str] = None
    is_comments_gif_composer_enabled: Optional[bool] = None
    comment_inform_treatment: Optional[CommentInformTreatment] = None
    has_liked: Optional[bool] = None
    like_count: Optional[int] = None
    facepile_top_likers: Optional[List] = None
    top_likers: Optional[List] = None
    video_subtitles_locale: Optional[str] = None
    video_sticker_locales: Optional[List] = None
    is_dash_eligible: Optional[int] = None
    video_dash_manifest: Optional[str] = None
    video_codec: Optional[str] = None
    number_of_qualities: Optional[int] = None
    video_versions: Optional[List[VideoVersion]] = None
    video_duration: Optional[float] = None
    has_audio: Optional[bool] = None
    clips_tab_pinned_user_ids: Optional[List] = None
    clips_metadata: Optional[ClipsMetadata] = None
    can_viewer_save: Optional[bool] = None
    can_viewer_reshare: Optional[bool] = None
    shop_routing_user_id: Optional[Any] = None
    is_organic_product_tagging_eligible: Optional[bool] = None
    igbio_product: Optional[Any] = None
    featured_products: Optional[List] = None
    product_suggestions: Optional[List] = None
    is_reuse_allowed: Optional[bool] = None
    is_open_to_public_submission: Optional[bool] = None
    original_media_has_visual_reply_media: Optional[bool] = None
    open_carousel_submission_state: Optional[str] = None
    carousel_media_count: Optional[int] = None
    carousel_media: Optional[List[CarouselMediaItem]] = None
    carousel_media_pending_post_count: Optional[int] = None
    carousel_media_ids: Optional[List[int]] = None


class InstagramPost(BaseModel):
    num_results: Optional[int] = None
    more_available: Optional[bool] = None
    items: Optional[List[Item]] = None
    auto_load_more_enabled: Optional[bool] = None
    showQRModal: Optional[bool] = None
