# generated by datamodel-codegen:
#   timestamp: 2023-07-18T21:49:33+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import AnyUrl, BaseModel


class Caption(BaseModel):
    text: Optional[str] = None


class ConsumptionInfo(BaseModel):
    is_trending_in_clips: Optional[bool] = None


class IgArtist(BaseModel):
    profile_pic_url: Optional[AnyUrl] = None

    username: Optional[str] = None


class VideoVersion(BaseModel):
    height: Optional[int] = None
    url: Optional[AnyUrl] = None
    width: Optional[int] = None
    type: Optional[int] = None


class FriendshipStatus(BaseModel):
    following: Optional[bool] = None

    is_feed_favorite: Optional[bool] = None

    outgoing_request: Optional[bool] = None

    is_restricted: Optional[bool] = None
    is_bestie: Optional[bool] = None


class PageInfo(BaseModel):
    end_cursor: Optional[str] = None
    has_next_page: Optional[bool] = None
    has_previous_page: Optional[bool] = None


class OriginalSoundInfo(BaseModel):
    audio_asset_id: Optional[str] = None
    ig_artist: Optional[IgArtist] = None
    original_audio_title: Optional[str] = None
    is_explicit: Optional[bool] = None
    consumption_info: Optional[ConsumptionInfo] = None


class ImageVersions2(BaseModel):
    candidates: Optional[List[VideoVersion]] = None


class User(BaseModel):
    pk: Optional[str] = None
    username: Optional[str] = None
    profile_pic_url: Optional[AnyUrl] = None
    friendship_status: Optional[FriendshipStatus] = None
    is_private: Optional[bool] = None
    typename: Optional[str] = None
    is_unpublished: Optional[bool] = None


class ClipsMetadata(BaseModel):
    original_sound_info: Optional[OriginalSoundInfo] = None


class Media(BaseModel):
    pk: Optional[str] = None
    code: Optional[str] = None
    like_count: Optional[int] = None
    user: Optional[User] = None
    has_liked: Optional[bool] = None
    product_type: Optional[str] = None
    like_and_view_counts_disabled: Optional[bool] = None
    media_type: Optional[int] = None
    clips_metadata: Optional[ClipsMetadata] = None
    id: Optional[str] = None
    organic_tracking_token: Optional[str] = None
    caption: Optional[Caption] = None
    comment_count: Optional[int] = None
    can_viewer_reshare: Optional[bool] = None
    image_versions2: Optional[ImageVersions2] = None
    has_audio: Optional[bool] = None
    is_dash_eligible: Optional[int] = None
    number_of_qualities: Optional[int] = None
    video_dash_manifest: Optional[str] = None
    original_height: Optional[int] = None
    original_width: Optional[int] = None
    video_versions: Optional[List[VideoVersion]] = None
    taken_at: Optional[int] = None


class Node(BaseModel):
    media: Optional[Media] = None
    typename: Optional[str] = None


class Edge(BaseModel):
    node: Optional[Node] = None
    cursor: Optional[str] = None


class XdtAPIV1ClipsHomeConnection(BaseModel):
    edges: Optional[List[Edge]] = None
    page_info: Optional[PageInfo] = None


class IgReelsIndexRaw(BaseModel):
    xdt_api__v1__clips__home__connection: Optional[XdtAPIV1ClipsHomeConnection] = None
