# generated by datamodel-codegen:
#   timestamp: 2022-09-08T13:43:24+00:00


from __future__ import annotations

from typing import Any, Optional, List

from pydantic import BaseModel, Field

from .instagram_post2 import InstagramUserResponse  # noqa


class FriendshipStatus(BaseModel):
    following: Optional[bool] = None
    is_private: Optional[bool] = None
    incoming_request: Optional[bool] = None
    outgoing_request: Optional[bool] = None
    is_bestie: Optional[bool] = None
    is_restricted: Optional[bool] = None
    is_feed_favorite: Optional[bool] = None


class User(BaseModel):
    pk: Optional[int] = None
    username: Optional[str] = None
    full_name: Optional[str] = None
    is_private: Optional[bool] = None
    profile_pic_url: Optional[str] = None
    profile_pic_id: Optional[str] = None
    friendship_status: Optional[FriendshipStatus] = None
    is_verified: Optional[bool] = None


class Candidate(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class ImageVersions2(BaseModel):
    candidates: Optional[List[Candidate]] = None


class CommentInformTreatment(BaseModel):
    should_have_inform_treatment: Optional[bool] = None
    text: Optional[str] = None
    url: Optional[Any] = None
    action_type: Optional[Any] = None


class SharingFrictionInfo(BaseModel):
    should_have_sharing_friction: Optional[bool] = None
    bloks_app_url: Optional[Any] = None
    sharing_friction_payload: Optional[Any] = None


class User1(BaseModel):
    pk: Optional[int] = None
    is_private: Optional[bool] = None


class StoryFeedMedia(BaseModel):
    x: Optional[float] = None
    y: Optional[float] = None
    z: Optional[int] = None
    width: Optional[float] = None
    height: Optional[float] = None
    rotation: Optional[float] = None
    is_pinned: Optional[int] = None
    is_hidden: Optional[int] = None
    is_sticker: Optional[int] = None
    is_fb_sticker: Optional[int] = None
    media_id: Optional[str] = None
    product_type: Optional[str] = None
    media_code: Optional[str] = None
    clips_creation_entry_point: Optional[str] = None


class VideoVersion(BaseModel):
    type: Optional[int] = None
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None
    id: Optional[str] = None


class IgMention(BaseModel):
    account_id: Optional[str] = None
    username: Optional[str] = None
    full_name: Optional[str] = None
    profile_pic_url: Optional[str] = None


class StickerData(BaseModel):
    ig_mention: Optional[IgMention] = None


class BloksSticker(BaseModel):
    id: Optional[str] = None
    app_id: Optional[str] = None
    sticker_data: Optional[StickerData] = None
    bloks_sticker_type: Optional[str] = None


class StoryBloksSticker(BaseModel):
    bloks_sticker: Optional[BloksSticker] = None
    x: Optional[float] = None
    y: Optional[float] = None
    z: Optional[int] = None
    width: Optional[float] = None
    height: Optional[float] = None
    rotation: Optional[float] = None


class Item(BaseModel):
    accessibility_caption: Optional[str] = None
    can_reply: Optional[bool] = None
    can_reshare: Optional[bool] = None
    can_see_insights_as_brand: Optional[bool] = None
    can_send_custom_emojis: Optional[bool] = None
    can_send_prompt: Optional[bool] = None
    can_viewer_save: Optional[bool] = None
    caption_is_edited: Optional[bool] = None
    caption_position: Optional[float] = None
    caption: Optional[Any] = None
    client_cache_key: Optional[str] = None
    code: Optional[str] = None
    comment_inform_treatment: Optional[CommentInformTreatment] = None
    commerce_integrity_review_decision: Optional[Any] = None
    commerciality_status: Optional[str] = None
    deleted_reason: Optional[int] = None
    device_timestamp: Optional[int] = None
    expiring_at: Optional[int] = None
    filter_type: Optional[int] = None
    has_audio: Optional[bool] = None
    has_delayed_metadata: Optional[bool] = None
    has_shared_to_fb: Optional[int] = None
    id: Optional[str] = None
    image_versions2: Optional[ImageVersions2] = None
    integrity_review_decision: Optional[str] = None
    is_artist_pick: Optional[bool] = None
    is_dash_eligible: Optional[int] = None
    is_in_profile_grid: Optional[bool] = None
    is_organic_product_tagging_eligible: Optional[bool] = None
    is_paid_partnership: Optional[bool] = None
    is_reel_media: Optional[bool] = None
    is_unified_video: Optional[bool] = None
    is_visual_reply_commenter_notice_enabled: Optional[bool] = None
    like_and_view_counts_disabled: Optional[bool] = None
    media_type: Optional[int] = None
    music_metadata: Optional[Any] = None
    number_of_qualities: Optional[int] = None
    organic_tracking_token: Optional[str] = None
    original_height: Optional[int] = None
    original_media_has_visual_reply_media: Optional[bool] = None
    original_width: Optional[int] = None
    photo_of_you: Optional[bool] = None
    pk: Optional[str] = None
    product_type: Optional[str] = None
    profile_grid_control_enabled: Optional[bool] = None
    sharing_friction_info: Optional[SharingFrictionInfo] = None
    should_request_ads: Optional[bool] = None
    show_one_tap_fb_share_tooltip: Optional[bool] = None
    story_bloks_stickers: Optional[List[StoryBloksSticker]] = None
    story_feed_media: Optional[List[StoryFeedMedia]] = None
    story_static_models: Optional[list] = None
    supports_reel_reactions: Optional[bool] = None
    taken_at: Optional[int] = None
    user: Optional[User1] = None
    video_codec: Optional[str] = None
    video_dash_manifest: Optional[str] = None
    video_duration: Optional[float] = None
    video_versions: Optional[List[VideoVersion]] = None


class Field1574083(BaseModel):
    id: Optional[int] = None
    latest_reel_media: Optional[int] = None
    expiring_at: Optional[int] = None
    seen: Optional[int] = None
    can_reply: Optional[bool] = None
    can_gif_quick_reply: Optional[bool] = None
    can_reshare: Optional[bool] = None
    can_react_with_avatar: Optional[bool] = None
    reel_type: Optional[str] = None
    ad_expiry_timestamp_in_millis: Optional[Any] = None
    is_cta_sticker_available: Optional[Any] = None
    user: Optional[User] = None
    items: Optional[List[Item]] = None
    prefetch_count: Optional[int] = None
    media_count: Optional[int] = None
    media_ids: Optional[List[str]] = None


class Reels(BaseModel):
    field_1574083: Optional[Field1574083] = Field(alias="1574083")


class FriendshipStatus1(FriendshipStatus):
    pass


class User2(BaseModel):
    pk: Optional[int] = None
    username: Optional[str] = None
    full_name: Optional[str] = None
    is_private: Optional[bool] = None
    profile_pic_url: Optional[str] = None
    profile_pic_id: Optional[str] = None
    friendship_status: Optional[FriendshipStatus1] = None
    is_verified: Optional[bool] = None


class Candidate1(Candidate):
    pass


class ImageVersions21(BaseModel):
    candidates: Optional[List[Candidate1]] = None


class CommentInformTreatment1(CommentInformTreatment):
    pass


class SharingFrictionInfo1(SharingFrictionInfo):
    pass


class User3(User1):
    pass


class StoryFeedMedia1(StoryFeedMedia):
    pass


class VideoVersion1(VideoVersion):
    pass


class IgMention1(IgMention):
    pass


class StickerData1(BaseModel):
    ig_mention: Optional[IgMention1] = None


class BloksSticker1(BaseModel):
    id: Optional[str] = None
    app_id: Optional[str] = None
    sticker_data: Optional[StickerData1] = None
    bloks_sticker_type: Optional[str] = None


class StoryBloksSticker1(BaseModel):
    bloks_sticker: Optional[BloksSticker1] = None
    x: Optional[float] = None
    y: Optional[float] = None
    z: Optional[int] = None
    width: Optional[float] = None
    height: Optional[float] = None
    rotation: Optional[float] = None


class Item1(BaseModel):
    taken_at: Optional[int] = None
    pk: Optional[str] = None
    id: Optional[str] = None
    device_timestamp: Optional[int] = None
    media_type: Optional[int] = None
    code: Optional[str] = None
    client_cache_key: Optional[str] = None
    filter_type: Optional[int] = None
    accessibility_caption: Optional[str] = None
    is_unified_video: Optional[bool] = None
    should_request_ads: Optional[bool] = None
    caption_is_edited: Optional[bool] = None
    like_and_view_counts_disabled: Optional[bool] = None
    commerciality_status: Optional[str] = None
    is_paid_partnership: Optional[bool] = None
    is_visual_reply_commenter_notice_enabled: Optional[bool] = None
    original_media_has_visual_reply_media: Optional[bool] = None
    has_delayed_metadata: Optional[bool] = None
    image_versions2: Optional[ImageVersions21] = None
    original_width: Optional[int] = None
    original_height: Optional[int] = None
    caption_position: Optional[float] = None
    is_reel_media: Optional[bool] = None
    photo_of_you: Optional[bool] = None
    is_organic_product_tagging_eligible: Optional[bool] = None
    can_see_insights_as_brand: Optional[bool] = None
    caption: Optional[Any] = None
    comment_inform_treatment: Optional[CommentInformTreatment1] = None
    sharing_friction_info: Optional[SharingFrictionInfo1] = None
    can_viewer_save: Optional[bool] = None
    is_in_profile_grid: Optional[bool] = None
    profile_grid_control_enabled: Optional[bool] = None
    organic_tracking_token: Optional[str] = None
    expiring_at: Optional[int] = None
    has_shared_to_fb: Optional[int] = None
    product_type: Optional[str] = None
    deleted_reason: Optional[int] = None
    integrity_review_decision: Optional[str] = None
    commerce_integrity_review_decision: Optional[Any] = None
    music_metadata: Optional[Any] = None
    is_artist_pick: Optional[bool] = None
    user: Optional[User3] = None
    can_reshare: Optional[bool] = None
    can_reply: Optional[bool] = None
    can_send_prompt: Optional[bool] = None
    story_feed_media: Optional[List[StoryFeedMedia1]] = None
    story_static_models: Optional[list] = None
    supports_reel_reactions: Optional[bool] = None
    can_send_custom_emojis: Optional[bool] = None
    show_one_tap_fb_share_tooltip: Optional[bool] = None
    is_dash_eligible: Optional[int] = None
    video_dash_manifest: Optional[str] = None
    video_codec: Optional[str] = None
    number_of_qualities: Optional[int] = None
    video_versions: Optional[List[VideoVersion1]] = None
    has_audio: Optional[bool] = None
    video_duration: Optional[float] = None
    story_bloks_stickers: Optional[List[StoryBloksSticker1]] = None


class ReelsMedia(BaseModel):
    id: Optional[int] = None
    latest_reel_media: Optional[int] = None
    expiring_at: Optional[int] = None
    seen: Optional[int] = None
    can_reply: Optional[bool] = None
    can_gif_quick_reply: Optional[bool] = None
    can_reshare: Optional[bool] = None
    can_react_with_avatar: Optional[bool] = None
    reel_type: Optional[str] = None
    ad_expiry_timestamp_in_millis: Optional[Any] = None
    is_cta_sticker_available: Optional[Any] = None
    user: Optional[User2] = None
    items: Optional[List[Item1]] = None
    prefetch_count: Optional[int] = None
    media_count: Optional[int] = None
    media_ids: Optional[List[str]] = None


class InstaStoryModel(BaseModel):
    reels: Optional[Reels] = None
    reels_media: Optional[List[ReelsMedia]] = None
    status: Optional[str] = None
    created_at: Optional[int] = None


class StoryItem(BaseModel):
    id: Optional[str] = None
    is_video: Optional[bool] = None
    filename: Optional[str] = None
    url: Optional[str] = None
    taken_at: Optional[int] = None

    video_bytes: Optional[bytes] = Field(None, exclude=True)


class InstagramStoryResponse(BaseModel):
    author: Optional[InstagramUserResponse] = None
    items: Optional[List[StoryItem]] = []
    item_count: Optional[int] = None
    created_at: Optional[int] = None
