# generated by datamodel-codegen:
#   timestamp: 2023-02-06T16:09:58+00:00


from __future__ import annotations

from typing import Any, Optional, List, Dict

from pydantic import BaseModel


class CommentInformTreatment(BaseModel):
    should_have_inform_treatment: Optional[bool] = None
    text: Optional[str] = None
    url: Optional[Any] = None
    action_type: Optional[Any] = None


class Candidate(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class SharingFrictionInfo(BaseModel):
    should_have_sharing_friction: Optional[bool] = None
    bloks_app_url: Optional[Any] = None
    sharing_friction_payload: Optional[Any] = None


class Hashtag(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None


class FriendshipStatus(BaseModel):
    following: Optional[bool] = None
    is_private: Optional[bool] = None
    incoming_request: Optional[bool] = None
    outgoing_request: Optional[bool] = None
    is_bestie: Optional[bool] = None
    is_restricted: Optional[bool] = None
    is_feed_favorite: Optional[bool] = None


class TerritoryValidityPeriods(BaseModel):
    pass


class ItemUser(BaseModel):
    pk: Optional[str] = None
    is_private: Optional[bool] = None


class VideoVersion(BaseModel):
    type: Optional[int] = None
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None
    id: Optional[str] = None


class ImageVersions2(BaseModel):
    candidates: Optional[List[Candidate]] = None


class IgArtistClass(BaseModel):
    pk: Optional[str] = None
    pk_id: Optional[str] = None
    username: Optional[str] = None
    full_name: Optional[str] = None
    is_private: Optional[bool] = None
    is_verified: Optional[bool] = None
    profile_pic_id: Optional[str] = None
    profile_pic_url: Optional[str] = None
    friendship_status: Optional[FriendshipStatus] = None


class MusicAssetInfo(BaseModel):
    audio_cluster_id: Optional[str] = None
    id: Optional[str] = None
    title: Optional[str] = None
    sanitized_title: Optional[Any] = None
    subtitle: Optional[str] = None
    display_artist: Optional[str] = None
    artist_id: Optional[Any] = None
    cover_artwork_uri: Optional[str] = None
    cover_artwork_thumbnail_uri: Optional[str] = None
    progressive_download_url: Optional[str] = None
    reactive_audio_download_url: Optional[Any] = None
    fast_start_progressive_download_url: Optional[str] = None
    web_30s_preview_download_url: Optional[Any] = None
    highlight_start_times_in_ms: Optional[List[int]] = None
    is_explicit: Optional[bool] = None
    dash_manifest: Optional[Any] = None
    has_lyrics: Optional[bool] = None
    audio_asset_id: Optional[str] = None
    duration_in_ms: Optional[int] = None
    dark_message: Optional[Any] = None
    allows_saving: Optional[bool] = None
    territory_validity_periods: Optional[TerritoryValidityPeriods] = None
    ig_username: Optional[str] = None
    ig_artist: Optional[IgArtistClass] = None
    placeholder_profile_pic_url: Optional[str] = None
    should_mute_audio: Optional[bool] = None
    should_mute_audio_reason: Optional[str] = None
    should_mute_audio_reason_type: Optional[Any] = None
    is_bookmarked: Optional[bool] = None
    overlap_duration_in_ms: Optional[int] = None
    audio_asset_start_time_in_ms: Optional[int] = None
    allow_media_creation_with_music: Optional[bool] = None
    is_trending_in_clips: Optional[bool] = None
    formatted_clips_media_count: Optional[Any] = None
    streaming_services: Optional[Any] = None
    display_labels: Optional[Any] = None
    should_allow_music_editing: Optional[bool] = None


class Story(BaseModel):
    x: Optional[float] = None
    y: Optional[float] = None
    z: Optional[int] = None
    width: Optional[float] = None
    height: Optional[float] = None
    rotation: Optional[float] = None
    is_pinned: Optional[int] = None
    is_hidden: Optional[int] = None
    is_sticker: Optional[int] = None
    is_fb_sticker: Optional[int] = None
    hashtag: Optional[Hashtag] = None
    attribution: Optional[str] = None
    display_type: Optional[str] = None
    music_asset_info: Optional[MusicAssetInfo] = None


class Item(BaseModel):
    taken_at: Optional[int] = None
    pk: Optional[str] = None
    id: Optional[str] = None
    device_timestamp: Optional[int] = None
    media_type: Optional[int] = None
    code: Optional[str] = None
    client_cache_key: Optional[str] = None
    filter_type: Optional[int] = None
    is_unified_video: Optional[bool] = None
    should_request_ads: Optional[bool] = None
    original_media_has_visual_reply_media: Optional[bool] = None
    caption_is_edited: Optional[bool] = None
    like_and_view_counts_disabled: Optional[bool] = None
    commerciality_status: Optional[str] = None
    is_paid_partnership: Optional[bool] = None
    is_visual_reply_commenter_notice_enabled: Optional[bool] = None
    clips_tab_pinned_user_ids: Optional[list] = None
    has_delayed_metadata: Optional[bool] = None
    caption_position: Optional[float] = None
    is_reel_media: Optional[bool] = None
    photo_of_you: Optional[bool] = None
    is_organic_product_tagging_eligible: Optional[bool] = None
    can_see_insights_as_brand: Optional[bool] = None
    image_versions2: Optional[ImageVersions2] = None
    original_width: Optional[int] = None
    original_height: Optional[int] = None
    caption: Optional[Any] = None
    comment_inform_treatment: Optional[CommentInformTreatment] = None
    sharing_friction_info: Optional[SharingFrictionInfo] = None
    is_dash_eligible: Optional[int] = None
    video_dash_manifest: Optional[str] = None
    video_codec: Optional[str] = None
    number_of_qualities: Optional[int] = None
    video_versions: Optional[List[VideoVersion]] = None
    has_audio: Optional[bool] = None
    video_duration: Optional[float] = None
    can_viewer_save: Optional[bool] = None
    is_in_profile_grid: Optional[bool] = None
    profile_grid_control_enabled: Optional[bool] = None
    organic_tracking_token: Optional[str] = None
    expiring_at: Optional[int] = None
    imported_taken_at: Optional[int] = None
    has_shared_to_fb: Optional[int] = None
    product_type: Optional[str] = None
    deleted_reason: Optional[int] = None
    integrity_review_decision: Optional[str] = None
    commerce_integrity_review_decision: Optional[Any] = None
    music_metadata: Optional[Any] = None
    is_artist_pick: Optional[bool] = None
    user: Optional[ItemUser] = None
    can_reshare: Optional[bool] = None
    can_reply: Optional[bool] = None
    can_send_prompt: Optional[bool] = None
    is_first_take: Optional[bool] = None
    is_rollcall_v2: Optional[bool] = None
    can_play_spotify_audio: Optional[bool] = None
    created_from_add_yours_browsing: Optional[bool] = None
    story_static_models: Optional[list] = None
    supports_reel_reactions: Optional[bool] = None
    can_send_custom_emojis: Optional[bool] = None
    show_one_tap_fb_share_tooltip: Optional[bool] = None
    accessibility_caption: Optional[str] = None
    story_music_stickers: Optional[List[Story]] = None
    story_hashtags: Optional[List[Story]] = None


class Reels(BaseModel):
    id: Optional[str] = None
    latest_reel_media: Optional[int] = None
    expiring_at: Optional[int] = None
    seen: Optional[int] = None
    can_reply: Optional[bool] = None
    can_gif_quick_reply: Optional[bool] = None
    can_reshare: Optional[bool] = None
    can_react_with_avatar: Optional[bool] = None
    reel_type: Optional[str] = None
    ad_expiry_timestamp_in_millis: Optional[Any] = None
    is_cta_sticker_available: Optional[Any] = None
    user: Optional[IgArtistClass] = None
    items: Optional[List[Item]] = None
    prefetch_count: Optional[int] = None
    media_count: Optional[int] = None
    media_ids: Optional[List[str]] = None
    is_cacheable: Optional[bool] = None
    disabled_reply_types: Optional[List[str]] = None


class InstagramStorylinkRaw(BaseModel):
    reels: Optional[Dict[str, Reels]] = None
    reels_media: Optional[List[Reels]] = None
    status: Optional[str] = None
