# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2024-02-07T23:53:15+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class EligibleProfileTab(BaseModel):
    id: Optional[str] = None
    type: Optional[str] = None
    tab_type: Optional[int] = None
    name: Optional[str] = None
    is_default: Optional[bool] = None


class ContactPhoneCountry(BaseModel):
    code: Optional[str] = None
    phone_code: Optional[str] = None


class Partner(BaseModel):
    enable_profile_message: Optional[bool] = None
    contact_phone_country: Optional[ContactPhoneCountry] = None
    enable_profile_address: Optional[bool] = None
    profile_place: Optional[Any] = None
    contact_phone: Optional[str] = None
    contact_email: Optional[Any] = None


class ProfileCover(BaseModel):
    type: Optional[str] = None
    video: Optional[Any] = None
    source: Optional[str] = None
    source_id: Optional[Any] = None
    images: Optional[Any] = None


class Data(BaseModel):
    show_discovered_feed: Optional[bool] = None
    profile_discovered_public: Optional[bool] = None
    is_verified_merchant: Optional[bool] = None
    story_pin_count: Optional[int] = None
    is_tastemaker: Optional[bool] = None
    storefront_management_enabled: Optional[bool] = None
    eligible_profile_tabs: Optional[List[EligibleProfileTab]] = None
    instagram_data: Optional[Any] = None
    seo_noindex_reason: Optional[Any] = None
    impressum_url: Optional[Any] = None
    domain_verified: Optional[bool] = None
    has_shopping_showcase: Optional[bool] = None
    explicit_user_following_count: Optional[int] = None
    storefront_search_enabled: Optional[bool] = None
    last_pin_save_time: Optional[str] = None
    should_show_messaging: Optional[bool] = None
    is_private_profile: Optional[bool] = None
    group_board_count: Optional[int] = None
    show_engagement_tab: Optional[bool] = None
    about: Optional[str] = None
    image_small_url: Optional[str] = None
    show_impressum: Optional[bool] = None
    image_xlarge_url: Optional[str] = None
    id: Optional[str] = None
    seo_title: Optional[str] = None
    website_url: Optional[str] = None
    should_default_comments_off: Optional[bool] = None
    has_published_pins: Optional[bool] = None
    verified_identity: Optional[Dict[str, Any]] = None
    ads_only_profile_site: Optional[Any] = None
    domain_url: Optional[str] = None
    username: Optional[str] = None
    profile_reach: Optional[int] = None
    explicitly_followed_by_me: Optional[bool] = None
    image_medium_url: Optional[str] = None
    is_partner: Optional[bool] = None
    show_creator_profile: Optional[bool] = None
    follower_count: Optional[int] = None
    indexed: Optional[bool] = None
    has_showcase: Optional[bool] = None
    is_primary_website_verified: Optional[bool] = None
    image_large_url: Optional[str] = None
    blocked_by_me: Optional[bool] = None
    profile_views: Optional[int] = None
    is_inspirational_merchant: Optional[Any] = None
    first_name: Optional[str] = None
    has_catalog: Optional[bool] = None
    is_ads_only_profile: Optional[bool] = None
    partner: Optional[Partner] = None
    has_custom_board_sorting_order: Optional[bool] = None
    following_count: Optional[int] = None
    board_count: Optional[int] = None
    profile_cover: Optional[ProfileCover] = None
    native_pin_count: Optional[int] = None
    listed_website_url: Optional[Any] = None
    type: Optional[str] = None
    joined_communities_count: Optional[int] = None
    video_pin_count: Optional[int] = None
    pins_done_count: Optional[int] = None
    last_name: Optional[str] = None
    full_name: Optional[str] = None
    pin_count: Optional[int] = None
    pronouns: Optional[List] = None
    interest_following_count: Optional[int] = None
    seo_description: Optional[str] = None


class ResourceResponse(BaseModel):
    status: Optional[str] = None
    code: Optional[int] = None
    message: Optional[str] = None
    endpoint_name: Optional[str] = None
    data: Optional[Data] = None
    x_pinterest_sli_endpoint_name: Optional[str] = None
    http_status: Optional[int] = None


class AnalysisUa(BaseModel):
    app_type: Optional[int] = None
    browser_name: Optional[str] = None
    browser_version: Optional[str] = None
    device_type: Optional[int] = None
    device: Optional[str] = None
    os_name: Optional[str] = None
    os_version: Optional[str] = None


class User(BaseModel):
    unauth_id: Optional[str] = None
    ip_country: Optional[str] = None
    ip_region: Optional[str] = None


class ClientContext(BaseModel):
    analysis_ua: Optional[AnalysisUa] = None
    app_type_detailed: Optional[int] = None
    app_version: Optional[str] = None
    batch_exp: Optional[bool] = None
    browser_locale: Optional[str] = None
    browser_name: Optional[str] = None
    browser_type: Optional[int] = None
    browser_version: Optional[str] = None
    country: Optional[str] = None
    country_from_hostname: Optional[str] = None
    country_from_ip: Optional[str] = None
    csp_nonce: Optional[str] = None
    current_url: Optional[str] = None
    debug: Optional[bool] = None
    enabled_advertiser_countries: Optional[List[str]] = None
    facebook_token: Optional[Any] = None
    full_path: Optional[str] = None
    http_referrer: Optional[str] = None
    impersonator_user_id: Optional[Any] = None
    invite_code: Optional[str] = None
    invite_sender_id: Optional[str] = None
    is_authenticated: Optional[bool] = None
    is_bot: Optional[str] = None
    is_internal_ip: Optional[bool] = None
    is_full_page: Optional[bool] = None
    is_mobile_agent: Optional[bool] = None
    is_sterling_on_steroids: Optional[bool] = None
    is_tablet_agent: Optional[bool] = None
    language: Optional[str] = None
    locale: Optional[str] = None
    origin: Optional[str] = None
    path: Optional[str] = None
    placed_experiences: Optional[Any] = None
    referrer: Optional[Any] = None
    region_from_ip: Optional[str] = None
    request_host: Optional[str] = None
    request_identifier: Optional[str] = None
    social_bot: Optional[str] = None
    stage: Optional[str] = None
    sterling_on_steroids_ldap: Optional[Any] = None
    sterling_on_steroids_user_type: Optional[Any] = None
    unauth_id: Optional[str] = None
    seo_debug: Optional[bool] = None
    user_agent_can_use_native_app: Optional[bool] = None
    user_agent_platform: Optional[str] = None
    user_agent_platform_version: Optional[List[int]] = None
    user_agent: Optional[str] = None
    user: Optional[User] = None
    utm_campaign: Optional[Any] = None
    visible_url: Optional[str] = None


class Options(BaseModel):
    bookmarks: Optional[List[str]] = None
    username: Optional[str] = None
    field_set_key: Optional[str] = None


class Resource(BaseModel):
    name: Optional[str] = None
    options: Optional[Options] = None


class Model(BaseModel):
    resource_response: Optional[ResourceResponse] = None
    client_context: Optional[ClientContext] = None
    resource: Optional[Resource] = None
    request_identifier: Optional[str] = None
