# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2024-02-08T00:04:56+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SwagMakeup(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class DopeMakeup(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class EdgyMakeup(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class EyeMakeupArt(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class GrungeMakeup(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class MakeupEyeliner(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class PrettyMakeup(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class ArtistryMakeup(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class MakeupInspo(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class MakeupLooks(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class MakeupIdeas(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class EyeMakeupTutorials(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class MakeupTutorials(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class BeautyMakeup(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class HairMakeup(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class GothicMakeup(BaseModel):
    url: Optional[str] = None
    name: Optional[str] = None


class AnnotationsWithLinks(BaseModel):
    Swag_Makeup: Optional[SwagMakeup] = Field(None, alias="Swag Makeup")
    Dope_Makeup: Optional[DopeMakeup] = Field(None, alias="Dope Makeup")
    Edgy_Makeup: Optional[EdgyMakeup] = Field(None, alias="Edgy Makeup")
    Eye_Makeup_Art: Optional[EyeMakeupArt] = Field(None, alias="Eye Makeup Art")
    Grunge_Makeup: Optional[GrungeMakeup] = Field(None, alias="Grunge Makeup")
    Makeup_Eyeliner: Optional[MakeupEyeliner] = Field(None, alias="Makeup Eyeliner")
    Pretty_Makeup: Optional[PrettyMakeup] = Field(None, alias="Pretty Makeup")
    Artistry_Makeup: Optional[ArtistryMakeup] = Field(None, alias="Artistry Makeup")
    Makeup_Inspo: Optional[MakeupInspo] = Field(None, alias="Makeup Inspo")
    Makeup_Looks: Optional[MakeupLooks] = Field(None, alias="Makeup Looks")
    Makeup_Ideas: Optional[MakeupIdeas] = Field(None, alias="Makeup Ideas")
    Eye_Makeup_Tutorials: Optional[EyeMakeupTutorials] = Field(
        None, alias="Eye Makeup Tutorials"
    )
    Makeup_Tutorials: Optional[MakeupTutorials] = Field(None, alias="Makeup Tutorials")
    Beauty_Makeup: Optional[BeautyMakeup] = Field(None, alias="Beauty Makeup")
    Hair_Makeup: Optional[HairMakeup] = Field(None, alias="Hair Makeup")
    Gothic_Makeup: Optional[GothicMakeup] = Field(None, alias="Gothic Makeup")


class Field736x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field750x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field474x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field200x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field222x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field640x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field70x70(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field290x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field45x45(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field345x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field432x292(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field75x75(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field70x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field1200x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field200x150(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field400x300(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field400x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field60x60(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field170x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field564x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field236x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field30x30(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field216x146(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field600x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field237x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field192x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field136x136(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field90x90(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field150x150(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Field550x(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Originals(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Image(BaseModel):
    field_736x: Optional[Field736x] = Field(None, alias="736x")
    field_750x: Optional[Field750x] = Field(None, alias="750x")
    field_474x: Optional[Field474x] = Field(None, alias="474x")
    field_200x: Optional[Field200x] = Field(None, alias="200x")
    field_222x: Optional[Field222x] = Field(None, alias="222x")
    field_640x: Optional[Field640x] = Field(None, alias="640x")
    field_70x70: Optional[Field70x70] = Field(None, alias="70x70")
    field_290x: Optional[Field290x] = Field(None, alias="290x")
    field_45x45: Optional[Field45x45] = Field(None, alias="45x45")
    field_345x: Optional[Field345x] = Field(None, alias="345x")
    field_432x292: Optional[Field432x292] = Field(None, alias="432x292")
    field_75x75: Optional[Field75x75] = Field(None, alias="75x75")
    field_70x: Optional[Field70x] = Field(None, alias="70x")
    field_1200x: Optional[Field1200x] = Field(None, alias="1200x")
    field_200x150: Optional[Field200x150] = Field(None, alias="200x150")
    field_400x300: Optional[Field400x300] = Field(None, alias="400x300")
    field_400x: Optional[Field400x] = Field(None, alias="400x")
    field_60x60: Optional[Field60x60] = Field(None, alias="60x60")
    field_170x: Optional[Field170x] = Field(None, alias="170x")
    field_564x: Optional[Field564x] = Field(None, alias="564x")
    field_236x: Optional[Field236x] = Field(None, alias="236x")
    field_30x30: Optional[Field30x30] = Field(None, alias="30x30")
    field_216x146: Optional[Field216x146] = Field(None, alias="216x146")
    field_600x: Optional[Field600x] = Field(None, alias="600x")
    field_237x: Optional[Field237x] = Field(None, alias="237x")
    field_192x: Optional[Field192x] = Field(None, alias="192x")
    field_136x136: Optional[Field136x136] = Field(None, alias="136x136")
    field_90x90: Optional[Field90x90] = Field(None, alias="90x90")
    field_150x150: Optional[Field150x150] = Field(None, alias="150x150")
    field_550x: Optional[Field550x] = Field(None, alias="550x")
    originals: Optional[Originals] = None


class SeoRelatedInterest(BaseModel):
    name: Optional[str] = None
    url: Optional[str] = None
    origin_interest_id: Optional[int] = None
    translated_interest_id: Optional[Any] = None
    image: Optional[Image] = None


class CanonicalPin(BaseModel):
    id: Optional[str] = None


class SeoBreadcrumb(BaseModel):
    name: Optional[str] = None
    url: Optional[str] = None


class PinJoin(BaseModel):
    shopping_klp_urls: Optional[Any] = None
    visual_annotation: Optional[List[str]] = None
    annotations_with_links: Optional[AnnotationsWithLinks] = None
    seo_related_interests: Optional[List[SeoRelatedInterest]] = None
    canonical_pin: Optional[CanonicalPin] = None
    seo_canonical_domain: Optional[str] = None
    seo_breadcrumbs: Optional[List[SeoBreadcrumb]] = None
    seo_canonical_url: Optional[str] = None


class ReactionCounts(BaseModel):
    field_1: Optional[int] = Field(None, alias="1")
    field_11: Optional[int] = Field(None, alias="11")
    field_13: Optional[int] = Field(None, alias="13")


class RecommendScore(BaseModel):
    score: Optional[float] = None
    count: Optional[int] = None


class DidItData(BaseModel):
    responses_count: Optional[int] = None
    images_count: Optional[int] = None
    videos_count: Optional[int] = None
    rating: Optional[int] = None
    user_count: Optional[int] = None
    recommended_count: Optional[int] = None
    recommend_scores: Optional[List[RecommendScore]] = None
    type: Optional[str] = None
    details_count: Optional[int] = None
    tags: Optional[List] = None


class AggregatedStats(BaseModel):
    saves: Optional[int] = None
    done: Optional[int] = None


class AggregatedPinData(BaseModel):
    comment_count: Optional[int] = None
    did_it_data: Optional[DidItData] = None
    id: Optional[str] = None
    is_shop_the_look: Optional[bool] = None
    aggregated_stats: Optional[AggregatedStats] = None


class Component(BaseModel):
    type: Optional[str] = None
    content: Optional[str] = None


class FormattedDescription(BaseModel):
    components: Optional[List[Component]] = None


class Field60x601(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class Field136x1361(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class Field170x1(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class Field236x1(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class Field474x1(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class Field564x1(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class Field736x1(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class Field600x315(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class Orig(BaseModel):
    width: Optional[int] = None
    height: Optional[int] = None
    url: Optional[str] = None


class Images(BaseModel):
    field_60x60: Optional[Field60x601] = Field(None, alias="60x60")
    field_136x136: Optional[Field136x1361] = Field(None, alias="136x136")
    field_170x: Optional[Field170x1] = Field(None, alias="170x")
    field_236x: Optional[Field236x1] = Field(None, alias="236x")
    field_474x: Optional[Field474x1] = Field(None, alias="474x")
    field_564x: Optional[Field564x1] = Field(None, alias="564x")
    field_736x: Optional[Field736x1] = Field(None, alias="736x")
    field_600x315: Optional[Field600x315] = Field(None, alias="600x315")
    orig: Optional[Orig] = None


class Pinner(BaseModel):
    full_name: Optional[str] = None
    ads_only_profile_site: Optional[Any] = None
    image_medium_url: Optional[str] = None
    followed_by_me: Optional[bool] = None
    verified_identity: Optional[Dict[str, Any]] = None
    domain_url: Optional[Any] = None
    id: Optional[str] = None
    follower_count: Optional[int] = None
    first_name: Optional[str] = None
    blocked_by_me: Optional[bool] = None
    is_default_image: Optional[bool] = None
    image_small_url: Optional[str] = None
    is_verified_merchant: Optional[bool] = None
    type: Optional[str] = None
    username: Optional[str] = None
    domain_verified: Optional[bool] = None
    indexed: Optional[bool] = None
    explicitly_followed_by_me: Optional[bool] = None
    is_ads_only_profile: Optional[bool] = None


class OfficialUser(BaseModel):
    full_name: Optional[str] = None
    ads_only_profile_site: Optional[Any] = None
    image_medium_url: Optional[str] = None
    followed_by_me: Optional[bool] = None
    verified_identity: Optional[Dict[str, Any]] = None
    domain_url: Optional[str] = None
    id: Optional[str] = None
    follower_count: Optional[int] = None
    first_name: Optional[str] = None
    blocked_by_me: Optional[bool] = None
    is_default_image: Optional[bool] = None
    image_small_url: Optional[str] = None
    is_verified_merchant: Optional[bool] = None
    type: Optional[str] = None
    username: Optional[str] = None
    domain_verified: Optional[bool] = None
    indexed: Optional[bool] = None
    explicitly_followed_by_me: Optional[bool] = None
    is_ads_only_profile: Optional[bool] = None


class LinkDomain(BaseModel):
    official_user: Optional[OfficialUser] = None


class Owner(BaseModel):
    full_name: Optional[str] = None
    ads_only_profile_site: Optional[Any] = None
    image_medium_url: Optional[str] = None
    followed_by_me: Optional[bool] = None
    verified_identity: Optional[Dict[str, Any]] = None
    domain_url: Optional[Any] = None
    id: Optional[str] = None
    follower_count: Optional[int] = None
    first_name: Optional[str] = None
    blocked_by_me: Optional[bool] = None
    is_default_image: Optional[bool] = None
    image_small_url: Optional[str] = None
    is_verified_merchant: Optional[bool] = None
    type: Optional[str] = None
    username: Optional[str] = None
    domain_verified: Optional[bool] = None
    indexed: Optional[bool] = None
    explicitly_followed_by_me: Optional[bool] = None
    is_ads_only_profile: Optional[bool] = None


class Board(BaseModel):
    collaborated_by_me: Optional[bool] = None
    followed_by_me: Optional[bool] = None
    url: Optional[str] = None
    image_cover_url: Optional[str] = None
    access: Optional[List] = None
    owner: Optional[Owner] = None
    id: Optional[str] = None
    pin_thumbnail_urls: Optional[List[str]] = None
    name: Optional[str] = None
    layout: Optional[str] = None
    image_thumbnail_url: Optional[str] = None
    category: Optional[str] = None
    description: Optional[str] = None
    type: Optional[str] = None
    is_collaborative: Optional[bool] = None
    privacy: Optional[str] = None
    map_id: Optional[str] = None


class CloseupAttribution(BaseModel):
    full_name: Optional[str] = None
    ads_only_profile_site: Optional[Any] = None
    image_medium_url: Optional[str] = None
    followed_by_me: Optional[bool] = None
    verified_identity: Optional[Dict[str, Any]] = None
    domain_url: Optional[str] = None
    id: Optional[str] = None
    follower_count: Optional[int] = None
    first_name: Optional[str] = None
    blocked_by_me: Optional[bool] = None
    is_default_image: Optional[bool] = None
    image_small_url: Optional[str] = None
    is_verified_merchant: Optional[bool] = None
    type: Optional[str] = None
    username: Optional[str] = None
    domain_verified: Optional[bool] = None
    indexed: Optional[bool] = None
    explicitly_followed_by_me: Optional[bool] = None
    is_ads_only_profile: Optional[bool] = None


class NativeCreator(BaseModel):
    full_name: Optional[str] = None
    ads_only_profile_site: Optional[Any] = None
    image_medium_url: Optional[str] = None
    followed_by_me: Optional[bool] = None
    verified_identity: Optional[Dict[str, Any]] = None
    domain_url: Optional[Any] = None
    id: Optional[str] = None
    follower_count: Optional[int] = None
    first_name: Optional[str] = None
    blocked_by_me: Optional[bool] = None
    is_default_image: Optional[bool] = None
    image_small_url: Optional[str] = None
    is_verified_merchant: Optional[bool] = None
    type: Optional[str] = None
    username: Optional[str] = None
    domain_verified: Optional[bool] = None
    indexed: Optional[bool] = None
    explicitly_followed_by_me: Optional[bool] = None
    is_ads_only_profile: Optional[bool] = None


class OfferSummary(BaseModel):
    price_val: Optional[int] = None
    currency: Optional[str] = None
    price: Optional[str] = None
    in_stock: Optional[bool] = None
    availability: Optional[int] = None
    condition: Optional[int] = None
    standard_price: Optional[str] = None


class Offer(BaseModel):
    in_stock: Optional[bool] = None
    min_ad_price: Optional[Any] = None
    price_currency: Optional[str] = None
    id: Optional[str] = None
    price_value: Optional[int] = None
    name: Optional[Any] = None
    type: Optional[str] = None
    condition: Optional[int] = None
    availability: Optional[int] = None


class Product(BaseModel):
    offer_summary: Optional[OfferSummary] = None
    variant_set: Optional[Any] = None
    videos: Optional[List] = None
    name: Optional[str] = None
    type: Optional[str] = None
    shipping_info: Optional[Dict[str, Any]] = None
    additional_images: Optional[Any] = None
    id: Optional[str] = None
    additional_images_per_spec: Optional[Any] = None
    purchase_url: Optional[Any] = None
    has_multi_images: Optional[bool] = None
    offers: Optional[List[Offer]] = None
    label_info: Optional[Dict[str, Any]] = None
    price_history_summary: Optional[Dict[str, Any]] = None


class AggregateRating(BaseModel):
    id: Optional[str] = None
    rating_distribution: Optional[List] = None
    name: Optional[Any] = None
    type: Optional[str] = None


class FaviconImages(BaseModel):
    orig: Optional[str] = None


class RichMetadata(BaseModel):
    url: Optional[Any] = None
    amp_valid: Optional[bool] = None
    link_status: Optional[Any] = None
    locale: Optional[Any] = None
    apple_touch_icon_images: Optional[Any] = None
    canonical_url: Optional[Any] = None
    apple_touch_icon_link: Optional[Any] = None
    id: Optional[str] = None
    amp_url: Optional[Any] = None
    description: Optional[str] = None
    products: Optional[List[Product]] = None
    aggregate_rating: Optional[AggregateRating] = None
    favicon_link: Optional[str] = None
    tracker: Optional[Any] = None
    type: Optional[str] = None
    favicon_images: Optional[FaviconImages] = None
    site_name: Optional[str] = None
    has_price_drop: Optional[bool] = None
    title: Optional[str] = None


class Section(BaseModel):
    slug: Optional[str] = None
    id: Optional[str] = None
    title: Optional[str] = None


class Data(BaseModel):
    pin_join: Optional[PinJoin] = None
    access: Optional[List] = None
    music_attributions: Optional[List] = None
    link: Optional[str] = None
    third_party_pin_owner: Optional[Any] = None
    product_pin_data: Optional[Any] = None
    should_mute: Optional[bool] = None
    seo_url: Optional[str] = None
    promoter: Optional[Any] = None
    tracked_link: Optional[str] = None
    method: Optional[str] = None
    shopping_flags: Optional[List[int]] = None
    dominant_color: Optional[str] = None
    tracking_params: Optional[str] = None
    type: Optional[str] = None
    via_pinner: Optional[Any] = None
    price_currency: Optional[str] = None
    reaction_counts: Optional[ReactionCounts] = None
    domain: Optional[str] = None
    mobile_link: Optional[Any] = None
    aggregated_pin_data: Optional[AggregatedPinData] = None
    is_repin: Optional[bool] = None
    alt_text: Optional[Any] = None
    formatted_description: Optional[FormattedDescription] = None
    is_quick_promotable_by_pinner: Optional[bool] = None
    videos: Optional[Any] = None
    is_native: Optional[bool] = None
    media_attribution: Optional[Any] = None
    category: Optional[str] = None
    embed: Optional[Any] = None
    images: Optional[Images] = None
    pinner: Optional[Pinner] = None
    promoted_is_removable: Optional[bool] = None
    creator_class: Optional[Any] = None
    link_domain: Optional[LinkDomain] = None
    sponsorship: Optional[Any] = None
    closeup_description: Optional[str] = None
    should_open_in_stream: Optional[bool] = None
    seo_description: Optional[str] = None
    pinned_to_board: Optional[Any] = None
    share_count: Optional[int] = None
    is_promotable: Optional[bool] = None
    shopping_rec_disabled: Optional[bool] = None
    is_quick_promotable: Optional[bool] = None
    origin_pinner: Optional[Any] = None
    is_playable: Optional[bool] = None
    repin_count: Optional[int] = None
    is_stale_product: Optional[bool] = None
    board: Optional[Board] = None
    comments_disabled: Optional[bool] = None
    is_promoted: Optional[bool] = None
    shuffle: Optional[Any] = None
    closeup_attribution: Optional[CloseupAttribution] = None
    is_video: Optional[bool] = None
    creator_class_instance: Optional[Any] = None
    image_medium_url: Optional[str] = None
    closeup_user_note: Optional[str] = None
    should_redirect_id_only_url_to_text_url: Optional[bool] = None
    id: Optional[str] = None
    description: Optional[str] = None
    story_pin_data_id: Optional[Any] = None
    seo_noindex_reason: Optional[Any] = None
    privacy: Optional[str] = None
    comment_count: Optional[int] = None
    created_at: Optional[str] = None
    seo_title: Optional[str] = None
    is_eligible_for_brand_catalog: Optional[bool] = None
    can_delete_did_it_and_comments: Optional[bool] = None
    native_creator: Optional[NativeCreator] = None
    description_html: Optional[str] = None
    title: Optional[str] = None
    content_sensitivity: Optional[Dict[str, Any]] = None
    rich_metadata: Optional[RichMetadata] = None
    is_eligible_for_aggregated_comments: Optional[bool] = None
    story_pin_data: Optional[Any] = None
    attribution: Optional[Any] = None
    buyable_product_availability: Optional[Any] = None
    grid_title: Optional[str] = None
    is_eligible_for_pdp: Optional[bool] = None
    hashtags: Optional[List] = None
    price_value: Optional[int] = None
    carousel_data: Optional[Any] = None
    section: Optional[Section] = None
    auto_alt_text: Optional[Any] = None
    image_signature: Optional[str] = None
    is_hidden: Optional[bool] = None
    did_it_disabled: Optional[bool] = None
    is_oos_product: Optional[bool] = None
    related_article: Optional[Dict[str, Any]] = None
    is_whitelisted_for_tried_it: Optional[bool] = None
    closeup_unified_description: Optional[str] = None


class ResourceResponse(BaseModel):
    status: Optional[str] = None
    code: Optional[int] = None
    message: Optional[str] = None
    endpoint_name: Optional[str] = None
    data: Optional[Data] = None
    x_pinterest_sli_endpoint_name: Optional[str] = None
    http_status: Optional[int] = None


class AnalysisUa(BaseModel):
    app_type: Optional[int] = None
    browser_name: Optional[str] = None
    browser_version: Optional[str] = None
    device_type: Optional[Any] = None
    device: Optional[str] = None
    os_name: Optional[str] = None
    os_version: Optional[str] = None


class User(BaseModel):
    unauth_id: Optional[str] = None
    ip_country: Optional[str] = None
    ip_region: Optional[str] = None


class ClientContext(BaseModel):
    analysis_ua: Optional[AnalysisUa] = None
    app_type_detailed: Optional[int] = None
    app_version: Optional[str] = None
    batch_exp: Optional[bool] = None
    browser_locale: Optional[str] = None
    browser_name: Optional[str] = None
    browser_type: Optional[int] = None
    browser_version: Optional[str] = None
    country: Optional[str] = None
    country_from_hostname: Optional[str] = None
    country_from_ip: Optional[str] = None
    csp_nonce: Optional[str] = None
    current_url: Optional[str] = None
    debug: Optional[bool] = None
    deep_link: Optional[str] = None
    enabled_advertiser_countries: Optional[List[str]] = None
    facebook_token: Optional[Any] = None
    full_path: Optional[str] = None
    http_referrer: Optional[str] = None
    impersonator_user_id: Optional[Any] = None
    invite_code: Optional[str] = None
    invite_sender_id: Optional[str] = None
    is_authenticated: Optional[bool] = None
    is_bot: Optional[str] = None
    is_internal_ip: Optional[bool] = None
    is_full_page: Optional[bool] = None
    is_mobile_agent: Optional[bool] = None
    is_sterling_on_steroids: Optional[bool] = None
    is_tablet_agent: Optional[bool] = None
    language: Optional[str] = None
    locale: Optional[str] = None
    origin: Optional[str] = None
    path: Optional[str] = None
    placed_experiences: Optional[Any] = None
    referrer: Optional[Any] = None
    region_from_ip: Optional[str] = None
    request_host: Optional[str] = None
    request_identifier: Optional[str] = None
    social_bot: Optional[str] = None
    stage: Optional[str] = None
    sterling_on_steroids_ldap: Optional[Any] = None
    sterling_on_steroids_user_type: Optional[Any] = None
    unauth_id: Optional[str] = None
    seo_debug: Optional[bool] = None
    user_agent_can_use_native_app: Optional[bool] = None
    user_agent_platform: Optional[str] = None
    user_agent_platform_version: Optional[Any] = None
    user_agent: Optional[str] = None
    user: Optional[User] = None
    utm_campaign: Optional[Any] = None
    visible_url: Optional[str] = None


class Options(BaseModel):
    bookmarks: Optional[List[str]] = None
    field_set_key: Optional[str] = None
    id: Optional[str] = None


class Resource(BaseModel):
    name: Optional[str] = None
    options: Optional[Options] = None


class Model(BaseModel):
    resource_response: Optional[ResourceResponse] = None
    client_context: Optional[ClientContext] = None
    resource: Optional[Resource] = None
    request_identifier: Optional[str] = None
