# generated by datamodel-codegen:
#   filename:  yes.json
#   timestamp: 2024-06-19T20:24:47+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class ZoomCover(BaseModel):
    field_240: Optional[str] = Field(None, alias="240")
    field_480: Optional[str] = Field(None, alias="480")
    field_720: Optional[str] = Field(None, alias="720")
    field_960: Optional[str] = Field(None, alias="960")


class VolumeInfo(BaseModel):
    Loudness: Optional[float] = None
    Peak: Optional[float] = None


class PlayAddr(BaseModel):
    DataSize: Optional[str] = None
    Uri: Optional[str] = None
    UrlList: Optional[List[str]] = None
    UrlKey: Optional[str] = None
    FileHash: Optional[str] = None
    FileCs: Optional[str] = None


class BitrateInfoItem(BaseModel):
    Bitrate: Optional[int] = None
    QualityType: Optional[int] = None
    GearName: Optional[str] = None
    PlayAddr: Optional[PlayAddr] = None
    CodecType: Optional[str] = None


class Video1(BaseModel):
    id: Optional[str] = None
    height: Optional[int] = None
    width: Optional[int] = None
    duration: Optional[int] = None
    ratio: Optional[str] = None
    cover: Optional[str] = None
    originCover: Optional[str] = None
    dynamicCover: Optional[str] = None
    playAddr: Optional[str] = None
    downloadAddr: Optional[str] = None
    shareCover: Optional[List[str]] = None
    reflowCover: Optional[str] = None
    bitrate: Optional[int] = None
    encodedType: Optional[str] = None
    format: Optional[str] = None
    videoQuality: Optional[str] = None
    encodeUserTag: Optional[str] = None
    codecType: Optional[str] = None
    definition: Optional[str] = None
    subtitleInfos: Optional[List] = None
    zoomCover: Optional[ZoomCover] = None
    volumeInfo: Optional[VolumeInfo] = None
    bitrateInfo: Optional[List[BitrateInfoItem]] = None


class Author(BaseModel):
    id: Optional[str] = None
    shortId: Optional[str] = None
    uniqueId: Optional[str] = None
    nickname: Optional[str] = None
    avatarLarger: Optional[str] = None
    avatarMedium: Optional[str] = None
    avatarThumb: Optional[str] = None
    signature: Optional[str] = None
    createTime: Optional[int] = None
    verified: Optional[bool] = None
    secUid: Optional[str] = None
    ftc: Optional[bool] = None
    relation: Optional[int] = None
    openFavorite: Optional[bool] = None
    commentSetting: Optional[int] = None
    duetSetting: Optional[int] = None
    stitchSetting: Optional[int] = None
    privateAccount: Optional[bool] = None
    secret: Optional[bool] = None
    isADVirtual: Optional[bool] = None
    roomId: Optional[str] = None
    uniqueIdModifyTime: Optional[int] = None
    ttSeller: Optional[bool] = None
    downloadSetting: Optional[int] = None
    recommendReason: Optional[str] = None
    nowInvitationCardUrl: Optional[str] = None
    nickNameModifyTime: Optional[int] = None
    isEmbedBanned: Optional[bool] = None
    canExpPlaylist: Optional[bool] = None
    suggestAccountBind: Optional[bool] = None


class PreciseDuration(BaseModel):
    preciseDuration: Optional[int] = None
    preciseShootDuration: Optional[int] = None
    preciseAuditionDuration: Optional[int] = None
    preciseVideoDuration: Optional[int] = None


class Music(BaseModel):
    id: Optional[str] = None
    title: Optional[str] = None
    playUrl: Optional[str] = None
    coverLarge: Optional[str] = None
    coverMedium: Optional[str] = None
    coverThumb: Optional[str] = None
    authorName: Optional[str] = None
    original: Optional[bool] = None
    duration: Optional[int] = None
    album: Optional[str] = None
    scheduleSearchTime: Optional[int] = None
    collected: Optional[bool] = None
    preciseDuration: Optional[PreciseDuration] = None


class Stats(BaseModel):
    diggCount: Optional[int] = None
    shareCount: Optional[int] = None
    commentCount: Optional[int] = None
    playCount: Optional[int] = None
    collectCount: Optional[str] = None


class StatsV2(BaseModel):
    diggCount: Optional[str] = None
    shareCount: Optional[str] = None
    commentCount: Optional[str] = None
    playCount: Optional[str] = None
    collectCount: Optional[str] = None
    repostCount: Optional[str] = None


class Content(BaseModel):
    desc: Optional[str] = None
    textExtra: Optional[List] = None


class ItemControl(BaseModel):
    can_repost: Optional[bool] = None


class OldVideo(BaseModel):
    id: Optional[str] = None
    desc: Optional[str] = None
    createTime: Optional[str] = None
    scheduleTime: Optional[int] = None
    video: Optional[Video1] = None
    author: Optional[Author] = None
    music: Optional[Music] = None
    challenges: Optional[List] = None
    stats: Optional[Stats] = None
    statsV2: Optional[StatsV2] = None
    warnInfo: Optional[List] = None
    originalItem: Optional[bool] = None
    officalItem: Optional[bool] = None
    textExtra: Optional[List] = None
    secret: Optional[bool] = None
    forFriend: Optional[bool] = None
    digged: Optional[bool] = None
    itemCommentStatus: Optional[int] = None
    takeDown: Optional[int] = None
    effectStickers: Optional[List] = None
    privateItem: Optional[bool] = None
    duetEnabled: Optional[bool] = None
    stitchEnabled: Optional[bool] = None
    stickersOnItem: Optional[List] = None
    shareEnabled: Optional[bool] = None
    comments: Optional[List] = None
    duetDisplay: Optional[int] = None
    stitchDisplay: Optional[int] = None
    indexEnabled: Optional[bool] = None
    diversificationLabels: Optional[List[str]] = None
    locationCreated: Optional[str] = None
    suggestedWords: Optional[List] = None
    contents: Optional[List[Content]] = None
    diversificationId: Optional[int] = None
    collected: Optional[bool] = None
    channelTags: Optional[List] = None
    item_control: Optional[ItemControl] = None
    IsAigc: Optional[bool] = None
    AIGCDescription: Optional[str] = None
